image:
  repository: quay.io/openvnf/sftp
  tag:        alpine-3.7
  pullPolicy: IfNotPresent
nameOverride:     ""
fullnameOverride: ""
service:
  enabled: true
  type:    ClusterIP
  port:    22
sftpConfig:
  username:  sftp
#  password:  {{{{ sftp_login_password }}}}
  encrypted: true
  uid:       {{{{ sftp_uid }}}}
  gid:       {{{{ sftp_gid }}}}
  hostKeys:
    secret:    sftp-private-key
    namespace: default
    keys:
      - key
  authorizedKeys:
    - "{{{{ sftp_login_public_key }}}}"
debug:
  enabled: true
  image:
    repository: quay.io/travelping/nettools
    tag:        v1.10.0
    pullPolicy: IfNotPresent
persistentVolume:
  enabled:      true
  annotations: { }
  accessModes:
    - ReadWriteOnce
  size:         {{{{ sftp_size }}}}
  storageClass: {{{{ storage_class }}}}
  subPath:      ""
vxlanController:
  enabled:       false
  annotationKey: vxlan.openvnf.org/networks
  metadataKey:   vxlan.openvnf.org
  image:
    repository: openvnf/kube-vxlan-controller-agent
    tag:        2.1.0
    pullPolicy: IfNotPresent
  network:       "vxeth0"
  ip: { }
  route: { }
  resources: { }
    # limits:
    #   cpu: 50m
    #   memory: 64Mi
    # requests:
  #   cpu: 50m
  #   memory: 64Mi
resources: { }
# resources:
#   sftp:
#     limits:
#       cpu: 100m
#       memory: 128Mi
#     requests:
#       cpu: 100m
#       memory: 128Mi
#   debug:
#     limits:
#       cpu: 100m
#       memory: 64Mi
#     requests:
#       cpu: 50m
#       memory: 32Mi
nodeSelector: { }
tolerations: [ ]
affinity: { }
