apiVersion: v1
kind:       Service
metadata:
  name: front
  labels:
  {{- include "geocode.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.front.ports.port }}
      targetPort: {{ .Values.front.ports.name }}
{{/*      protocol: {{ .Values.front.ports.protocol }}*/}}
      name: {{ .Values.front.ports.name }}

  selector:
  {{- include "geocode.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind:       Service
metadata:
  name: back
  labels:
  {{- include "geocode.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.back.ports.port }}
      targetPort: {{ .Values.back.ports.name }}
      protocol: {{ .Values.back.ports.protocol }}
      name: {{ .Values.back.ports.name }}
  selector:
  {{- include "geocode.selectorLabels" . | nindent 4 }}
