{
 "title": "2.Credentials",
 "description": "SSP Credential Dashboard",
 "tags": [ "SSP" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "source2", "label": "Data Source", "query": "${VAR_SOURCE2}" }
  ]
 },
 "panels": [
  {
   "title": "First Factor AuthN",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count (ssp_authn{credential1=~\"([a-zA-Z]+)\",source=~\"$source2\"}) by (credential1)",
     "legendFormat": "{{credential1}}"
    }
   ]
  },
  {
   "title": "Second Factor AuthN",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count (ssp_authn{credential2=~\"([a-zA-Z_]+)\",source=~\"$source2\"}) by (credential2)",
     "legendFormat": "{{credential2}}"
    }
   ]
  },
  {
   "title": "PASSWORD Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count (ssp_authn{credential1=\"ldap\",source=~\"$source2\"}) ",
     "legendFormat": "1st Factor"
    },
    {
     "expr": "count(ssp_authn{credential2=\"ldap\",source=~\"$source2\"})",
     "legendFormat": "2nd Factor"
    },
    {
     "expr": "count (ssp_cred_error{factorType=~\"ldap\",source=~\"$source2\"})",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "TOTP / PUSH Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count (ssp_authn{credential1=\"totp_push\",source=~\"$source2\"})",
     "legendFormat": "1st Factor"
    },
    {
     "expr": "count (ssp_authn{credential2=\"totp_push\",source=~\"$source2\"})",
     "legendFormat": "2nd Factor"
    },
    {
     "expr": "count (ssp_cred_error{factorType=~\"totp_push\",source=~\"$source2\"})",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "SMS Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(ssp_authn{credential1=\"sms\",source=~\"$source2\"})",
     "legendFormat": "1st Factor"
    },
    {
     "expr": "count (ssp_authn{credential2=\"sms\",source=~\"$source2\"})",
     "legendFormat": "2nd Factor"
    },
    {
     "expr": "count (ssp_cred_error{factorType=~\"sms\",source=~\"$source2\"})",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Email Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count (ssp_authn{credential1=\"email\",source=~\"$source2\"})",
     "legendFormat": "1st Factor"
    },
    {
     "expr": "count (ssp_authn{credential2=\"email\",source=~\"$source2\"})",
     "legendFormat": "2nd Factor"
    },
    {
     "expr": "count (ssp_cred_error{factorType=~\"email\",source=~\"$source2\"})",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "FIDO Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count (ssp_authn{credential1=\"FIDO\",source=~\"$source2\"})",
     "legendFormat": "1st Factor"
    },
    {
     "expr": "count (ssp_authn{credential2=\"FIDO\",source=~\"$source2\"})",
     "legendFormat": "2nd Factor"
    },
    {
     "expr": "count (ssp_cred_error{factorType=~\"FIDO\",source=~\"$source2\"})",
     "legendFormat": "Errors"
    }
   ]
  }
 ]
}