{
 "title": "App Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group_name",
    "label": "group_name",
    "query": "query_result(container_cpu_system_seconds_total)"
   },
   {
    "name": "app_name",
    "label": "app_name",
    "query": "query_result(container_cpu_system_seconds_total)"
   }
  ]
 },
 "panels": [
  { "type": "yesoreyeram-boomtheme-panel", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Cumulative Transmission (Packet)",
   "type": "graph",
   "description": "Cumulative count of packets transmitted",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_network_transmit_packets_total{namespace=\"#team:[[group_name]]#\", pod_name=~\"#project:[[app_name]]#.*\"}",
     "legendFormat": "transmit_packets_total"
    }
   ]
  },
  {
   "title": "Transmission Error Rate (Packet)",
   "type": "singlestat",
   "description": "(Count of dropped packets) / (Packets of transmission), in the time range",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "delta(container_network_transmit_packets_dropped_total{namespace=\"#team:[[group_name]]#\", pod_name=~\"#project:[[app_name]]#.*\"}[$__range]) / delta(container_network_transmit_packets_total[$__range])"
    }
   ]
  },
  {
   "title": "Cumulative Transmission (Byte)",
   "type": "graph",
   "description": "Cumulative count of bytes transmitted",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_network_transmit_bytes_total{namespace=\"#team:[[group_name]]#\", pod_name=~\"#project:[[app_name]]#.*\"}",
     "legendFormat": "transmit_total"
    }
   ]
  },
  {
   "title": "Transmission Error Rate (Byte)",
   "type": "singlestat",
   "description": "(Count of errors) / (Bytes of transmission), in the time range",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "delta(container_network_transmit_errors_total{namespace=\"#team:[[group_name]]#\", pod_name=~\"#project:[[app_name]]#.*\"}[$__range]) / delta(container_network_transmit_bytes_total[$__range])"
    }
   ]
  },
  {
   "title": "Cumulative Receipt (Packet)",
   "type": "graph",
   "description": "Cumulative count of packets received",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_network_receive_packets_total{namespace=\"#team:[[group_name]]#\", pod_name=~\"#project:[[app_name]]#.*\"}",
     "legendFormat": "receive_packets_total"
    }
   ]
  },
  {
   "title": "Receipt Error Rate (Packet)",
   "type": "singlestat",
   "description": "(Count of dropped packets) / (Packets of receipt), in the time range",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "delta(container_network_receive_packets_dropped_total{namespace=\"#team:[[group_name]]#\", pod_name=~\"#project:[[app_name]]#.*\"}[$__range]) / delta(container_network_receive_packets_total[$__range])"
    }
   ]
  },
  {
   "title": "Cumulative Receipt (Byte)",
   "type": "graph",
   "description": "Cumulative count of bytes received",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{namespace=\"#team:[[group_name]]#\", pod_name=~\"#project:[[app_name]]#.*\"}",
     "legendFormat": "receive_total"
    }
   ]
  },
  {
   "title": "Receipt Error Rate (Byte)",
   "type": "singlestat",
   "description": "(Count of errors) / (Bytes of receipt), in the time range",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "delta(container_network_receive_errors_total{namespace=\"#team:[[group_name]]#\", pod_name=~\"#project:[[app_name]]#.*\"}[$__range]) / delta(container_network_receive_bytes_total[$__range])"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Size",
   "type": "graph",
   "description": "Size of current working set / total memory usage",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"#team:[[group_name]]#\", image!=\"\", name!~\"k8s_POD_.*\", pod_name=~\"#project:[[app_name]]#.*\"}",
     "legendFormat": "working_set"
    },
    {
     "expr": "container_memory_usage_bytes{namespace=\"#team:[[group_name]]#\", image!=\"\", name!~\"k8s_POD_.*\", pod_name=~\"#project:[[app_name]]#.*\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Maximum",
   "type": "singlestat",
   "description": "Maximum memory usage recorded",
   "gridPos": { "h": 8, "w": 2, "x": 15, "y": 21 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{namespace=\"#team:[[group_name]]#\", image!=\"\", name!~\"k8s_POD_.*\", pod_name=~\"#project:[[app_name]]#.*\"}",
     "legendFormat": "max_usage"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "gauge",
   "description": "Current memory saturation (usage / limit) for the container",
   "gridPos": { "h": 8, "w": 5, "x": 17, "y": 21 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"#team:[[group_name]]#\", image!=\"\", name!~\"k8s_POD_.*\", pod_name=~\"#project:[[app_name]]#.*\"} / container_spec_memory_limit_bytes",
     "legendFormat": "sturation"
    }
   ]
  },
  {
   "title": "Allocation Failure",
   "type": "singlestat",
   "description": "Count of memory allocation failures in the time range",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 21 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "expr": "container_memory_failures_total{namespace=\"#team:[[group_name]]#\", scope=\"container\", type=\"pgfault\", container_name=\"#project:[[app_name]]#\"}",
     "legendFormat": "failures_total"
    }
   ]
  },
  {
   "title": "Limit Hit",
   "type": "singlestat",
   "description": "Number of memory usage hits limits in the time range",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 25 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "expr": "container_memory_failcnt{namespace=\"#team:[[group_name]]#\", image!=\"\", name!~\"k8s_POD_.*\", pod_name=~\"#project:[[app_name]]#.*\"}",
     "legendFormat": "failcnt"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "User Time",
   "type": "singlestat",
   "description": "User cpu time consumed in the time range",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 30 },
   "format": "dtdurations",
   "valueName": "diff",
   "targets": [
    {
     "expr": "container_cpu_user_seconds_total{namespace=\"#team:[[group_name]]#\", image!=\"\", name!~\"k8s_POD_.*\", pod_name=~\"#project:[[app_name]]#.*\"}"
    }
   ]
  },
  {
   "title": "Real Time",
   "type": "singlestat",
   "description": "Cpu time consumed in the time range",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 30 },
   "format": "dtdurations",
   "valueName": "diff",
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{namespace=\"#team:[[group_name]]#\", image!=\"\", name!~\"k8s_POD_.*\", pod_name=~\"#project:[[app_name]]#.*\"}",
     "legendFormat": "usage_total"
    }
   ]
  },
  {
   "title": "System Time",
   "type": "singlestat",
   "description": "System cpu time consumed in the time range",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 30 },
   "format": "dtdurations",
   "valueName": "diff",
   "targets": [
    {
     "expr": "container_cpu_system_seconds_total{namespace=\"#team:[[group_name]]#\", image!=\"\", name!~\"k8s_POD_.*\", pod_name=~\"#project:[[app_name]]#.*\"}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "singlestat",
   "description": "Average load of  CPU in the last 10s (The spark line shows the history information)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{namespace=\"#team:[[group_name]]#\", image!=\"\", name!~\"k8s_POD_.*\", pod_name=~\"#project:[[app_name]]#.*\"}",
     "legendFormat": "load_average_10s"
    }
   ]
  },
  { "title": "File System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Reads Completed",
   "type": "singlestat",
   "description": "Count of reads completed in the time range. The spark line shows cumulative count of reads completed.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "expr": "container_fs_reads_total{namespace=\"#team:[[group_name]]#\", image!=\"\", name!~\"k8s_POD_.*\", device=\"/dev/vda1\", pod_name=~\"#project:[[app_name]]#.*\"}",
     "legendFormat": "reads_total"
    }
   ]
  },
  {
   "title": "Writes Completed",
   "type": "singlestat",
   "description": "Count of writes completed in the time range. The spark line shows cumulative count of writes completed.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 37 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "expr": "container_fs_writes_total{namespace=\"#team:[[group_name]]#\", image!=\"\", name!~\"k8s_POD_.*\", device=\"/dev/vda1\", pod_name=~\"#project:[[app_name]]#.*\"}",
     "legendFormat": "writes_total"
    }
   ]
  },
  {
   "title": "IO Current",
   "type": "singlestat",
   "description": "Number of I/Os currently in progress.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "container_fs_io_current{namespace=\"#team:[[group_name]]#\", image!=\"\", name!~\"k8s_POD_.*\", pod_name=~\"#project:[[app_name]]#.*\"}",
     "legendFormat": "io_current"
    }
   ]
  },
  {
   "title": "Inodes Total",
   "type": "singlestat",
   "description": "The total number of current inodes.\nThe spark line shows history information.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "container_fs_inodes_total{namespace=\"#team:[[group_name]]#\", image!=\"\", name!~\"k8s_POD_.*\", pod_name=~\"#project:[[app_name]]#.*\"}",
     "legendFormat": "inodes_total"
    }
   ]
  },
  {
   "title": "Cumulative Time",
   "type": "graph",
   "description": "Cumulative count of seconds spent doing I/Os, reading, and writing from the container was created.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "container_fs_io_time_seconds_total{namespace=\"#team:[[group_name]]#\", image!=\"\", name!~\"k8s_POD_.*\", pod_name=~\"#project:[[app_name]]#.*\"}",
     "legendFormat": "io_time_total"
    },
    {
     "expr": "container_fs_read_seconds_total{namespace=\"#team:[[group_name]]#\", image!=\"\", name!~\"k8s_POD_.*\", pod_name=~\"#project:[[app_name]]#.*\"}",
     "legendFormat": "read_total"
    },
    {
     "expr": "container_fs_write_seconds_total{namespace=\"#team:[[group_name]]#\", image!=\"\", name!~\"k8s_POD_.*\", pod_name=~\"#project:[[app_name]]#.*\"}",
     "legendFormat": "write_total"
    },
    {
     "expr": "container_fs_io_time_weighted_seconds_total{namespace=\"#team:[[group_name]]#\", image!=\"\", name!~\"k8s_POD_.*\", pod_name=~\"#project:[[app_name]]#.*\"}",
     "legendFormat": "io_time_weighted_total"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "gauge",
   "description": "(usage / limit) of the current file system.",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 45 },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{namespace=\"#team:[[group_name]]#\", image!=\"\", name!~\"k8s_POD_.*\", pod_name=~\"#project:[[app_name]]#.*\"} / container_fs_limit_bytes",
     "legendFormat": "saturation"
    }
   ]
  },
  {
   "title": "Cumulativev Count of Read/Write",
   "type": "graph",
   "description": "Cumulative count of read/write.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_reads_bytes_total{namespace=\"#team:[[group_name]]#\", image!=\"\", name!~\"k8s_POD_.*\", pod_name=~\"#project:[[app_name]]#.*\"}",
     "legendFormat": "reads_total"
    },
    {
     "expr": "container_fs_writes_bytes_total{namespace=\"#team:[[group_name]]#\", image!=\"\", name!~\"k8s_POD_.*\", pod_name=~\"#project:[[app_name]]#.*\"}",
     "legendFormat": "writes_total"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "singlestat",
   "description": "Start time of the container since unix epoch",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 53 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "container_start_time_seconds{namespace=\"#team:[[group_name]]#\", image!=\"\", name!~\"k8s_POD_.*\", pod_name=~\"#project:[[app_name]]#.*\"} * 1000"
    }
   ]
  }
 ]
}