{
 "title": "EdgeRouter",
 "description": "EdgeRouter Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    { "expr": "hrSystemUptime / 100" }
   ]
  },
  {
   "title": "eth0 Rx",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifName=\"eth0\"}[5m]) * 8"
    }
   ]
  },
  {
   "title": "eth0 Tx",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "format": "bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{ifName=\"eth0\"}[5m]) * 8"
    }
   ]
  },
  {
   "title": "Total Rx",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "ifHCInOctets{ifName=\"eth0\"}"
    }
   ]
  },
  {
   "title": "Total Tx",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "ifHCOutOctets{ifName=\"eth0\"}"
    }
   ]
  },
  {
   "title": "eth0 Download",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifName=\"eth0\"}[5m]) * 8",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "eth0 Upload",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{ifName=\"eth0\"}[5m]) * 8",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "100 - ssCpuIdle", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "memTotalFree / memTotalReal * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}