{
 "title": "EasyBroadcast P2P Performance Dashboard",
 "description": "Easybroadcast P2P performance Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "room",
    "query": "label_values(room_events, room)"
   },
   {
    "name": "libVersion",
    "query": "label_values(perf_counter, exported_version)"
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Performance P2P percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(perf_counter{upload=\"false\", mode=\"v2v\", exported_version=\"$libVersion\"}[5m])) by (room) / sum(rate(perf_counter{upload=\"false\"}[5m])) by (room)",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Number of peers in rooms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(num_peers) by (room)", "legendFormat": "{{room}}" }
   ]
  },
  {
   "title": "Register failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(room_events{module=\"reg\", evt!=\"suc\"}[5m])) by (registered)",
     "legendFormat": "{{registered}}"
    }
   ]
  },
  {
   "title": "Lib version last 5 minutes agg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(lib_version[60m])) by (exported_version)",
     "legendFormat": "{{exported_version}}-{{room}}"
    }
   ]
  },
  {
   "title": "Newest version min percentage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum(delta(lib_version{exported_version=\"$libVersion\"}[10m])) / sum(delta(lib_version[10m])) * 100"
    }
   ]
  },
  {
   "title": "Current Peers",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 9 },
   "targets": [
    { "expr": "sum(num_peers)\n" }
   ]
  },
  {
   "title": "front-manager go routines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{app=\"front-manager-sf\"}) by (kubernetes_pod_name)\n",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Allocated Memory Front manager",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_memstats_alloc_bytes_total{app=\"front-manager-sf\"}[10m])) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Second Rate of message send / received of kafka",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_message_counter{action=\"sent\"}[1m]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(rate(kafka_message_counter{action=\"rcvd\", topic=~\"manager_front-manager-sf-.*|manager_all\"}[1m]))",
     "legendFormat": "Received"
    }
   ]
  },
  { "title": "Room Info $room", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }, "repeat": "room" },
  {
   "title": "Performance P2P percentage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(perf_counter{upload=\"false\", mode=\"v2v\", room=\"$room\", exported_version=~\"$libVersion\"}[5m])) / sum(rate(perf_counter{upload=\"false\", room=\"$room\",exported_version=\"$libVersion\"}[5m]))",
     "legendFormat": "download"
    },
    {
     "expr": "sum(rate(perf_counter{upload=\"true\", mode=\"v2v\", room=\"$room\", exported_version=~\"$libVersion\"}[5m])) / sum(rate(perf_counter{upload=\"false\", room=\"$room\", exported_version=\"$libVersion\"}[5m]))",
     "legendFormat": "upload"
    }
   ]
  },
  {
   "title": "Real time speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(perf_counter{room=\"$room\", exported_version=\"$libVersion\"}[5m])) by (mode, upload)",
     "legendFormat": "{{mode}}-{{upload}}"
    },
    {
     "expr": "sum(rate(perf_counter{upload=\"false\", room=\"$room\",  exported_version=\"$libVersion\"}[5m]))",
     "legendFormat": "Total download"
    },
    {
     "expr": "sum(rate(perf_counter{upload=\"true\", mode=\"v2v\", room=\"$room\",  exported_version=\"$libVersion\"}[5m])) / sum(rate(perf_counter{upload=\"false\", room=\"$room\",  exported_version=\"$libVersion\"}[5m])) - sum(rate(perf_counter{upload=\"false\", mode=\"v2v\", room=\"$room\"}[5m])) / sum(rate(perf_counter{upload=\"false\", room=\"$room\",  exported_version=\"$libVersion\"}[5m]))",
     "legendFormat": "Lost Chunk"
    }
   ]
  },
  {
   "title": "KB/s speed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(irate(msg_stats{room=\"$room\", type=\"size\", direction=\"w\"}[5m])) by (msg)",
     "legendFormat": "{{msg}}"
    },
    {
     "expr": "-sum(irate(msg_stats{room=\"$room\", type=\"size\", direction=\"r\"}[5m])) by (msg)",
     "legendFormat": "{{msg}}"
    }
   ]
  },
  {
   "title": "Current Peers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(num_peers{room=\"$room\"})\n"
    }
   ]
  },
  {
   "title": "Lib version last 5 minutes agg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(lib_version{room=\"$room\"}[5m])) by (exported_version)",
     "legendFormat": "{{exported_version}}-{{room}}"
    }
   ]
  },
  {
   "title": "Register Event success vs failure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 3, "x": 7, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(room_events{module=\"reg\", room=\"$room\", registered=\"false\"}[5m])) by (evt)",
     "legendFormat": "{{evt}}"
    }
   ]
  },
  {
   "title": "Message Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(msg_stats{room=\"$room\", type=\"cnt\", direction=\"w\"}[5m])) by (msg)",
     "legendFormat": "{{msg}}"
    },
    {
     "expr": "-sum(rate(msg_stats{room=\"$room\", type=\"cnt\", direction=\"r\"}[5m])) by (msg)",
     "legendFormat": "{{msg}}"
    }
   ]
  },
  {
   "title": "Violation of terms of services",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(room_events{module=\"vts\", room=\"$room\"}[5m])) by (evt)",
     "legendFormat": "{{evt}}"
    }
   ]
  },
  {
   "title": "$room peers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "num_peers{room=\"$room\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}