{
 "title": "Harbor-Monitoring",
 "description": "This is a simple Grafana Dashboard to display Host Metrics such CPU, Memory, DISK IO, Load Average, collected using the Node Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d"
   },
   { "name": "application_name", "label": "AppName", "query": "${VAR_APPLICATION_NAME}" }
  ]
 },
 "panels": [
  {
   "title": "Total CPUs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=~\"$application_name\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Statistics",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{job=~\"$application_name\",mode=\"system\"}[1m])) by (instance)",
     "legendFormat": "sys"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{job=~\"$application_name\",mode=\"user\"}[1m])) by (instance)",
     "legendFormat": "user"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{job=~\"$application_name\",mode=\"iowait\"}[1m])) by (instance)",
     "legendFormat": "iowait"
    }
   ]
  },
  {
   "title": "Load Avarage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=~\"$application_name\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{job=~\"$application_name\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{job=~\"$application_name\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=~\"$application_name\"}"
    }
   ]
  },
  {
   "title": "Filesystem Inodes Used",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "100 - ( node_filesystem_files_free{job=~\"$application_name\"} / node_filesystem_files{job=~\"$application_name\"} * 100 )",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 4, "y": 11 },
   "targets": [
    {
     "expr": "avg_over_time(node_filesystem_size_bytes{job=~\"$application_name\",fstype=~\"ext4\"}[1d])"
    },
    {
     "expr": "avg_over_time(node_filesystem_avail_bytes{job=~\"$application_name\",fstype=~\"ext4\"}[1d])"
    },
    {
     "expr": "1-(node_filesystem_avail_bytes{job=~\"$application_name\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{job=~\"$application_name\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "Memory Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 11 },
   "targets": [
    {
     "expr": "avg_over_time(node_memory_MemTotal_bytes {job=~\"$application_name\"}[$interval])"
    },
    {
     "expr": "node_memory_MemFree_bytes {job=~\"$application_name\"}"
    },
    {
     "expr": "avg_over_time(node_memory_MemAvailable_bytes {job=~\"$application_name\"}[$interval])"
    },
    {
     "expr": "avg_over_time(node_memory_Buffers_bytes {job=~\"$application_name\"}[$interval])"
    },
    {
     "expr": "avg_over_time(node_memory_Cached_bytes {job=~\"$application_name\"} [$interval])"
    },
    {
     "expr": "avg_over_time(node_memory_Active_bytes {job=~\"$application_name\"} [$interval])"
    },
    {
     "expr": "avg_over_time(node_memory_SwapCached_bytes {job=~\"$application_name\"}[$interval])"
    },
    {
     "expr": "avg_over_time(node_memory_SwapTotal_bytes {job=~\"$application_name\"}[$interval])"
    },
    {
     "expr": "avg_over_time(node_memory_SwapFree_bytes {job=~\"$application_name\"}[$interval])"
    }
   ]
  },
  {
   "title": "Disk_IO_Read/Write",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps", "label": "IO_Read/Write" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{job=~\"$application_name\"}[1m])",
     "legendFormat": "{{device}}_IO"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{job=~\"$application_name\"}[1m])",
     "legendFormat": "{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{job=~\"$application_name\"}[1m])",
     "legendFormat": "{{device}}_Write"
    }
   ]
  }
 ]
}