{
 "title": "Kubernetes Resource Requests (Not production)",
 "description": "Kubernetes Resource Requests (Not production)",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "CPU Cores",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "min(sum(\n  kube_node_labels{label_node_role_kubernetes_io_production!=\"true\"}\n  * on (node)\n  kube_node_status_allocatable_cpu_cores\n) by (instance))",
     "legendFormat": "Allocatable CPU Cores"
    },
    {
     "expr": "min(sum(\n  kube_node_labels{label_node_role_kubernetes_io_production!=\"true\"}\n  * on (node) group_right\n  kube_pod_container_resource_requests_cpu_cores\n) by (instance))",
     "legendFormat": "Requested CPU Cores"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(\n  kube_node_labels{label_node_role_kubernetes_io_production!=\"true\"}\n  * on (node) group_right\n  kube_pod_container_resource_requests_cpu_cores\n) by (instance))\n\n/ \n\nmin(sum(\n  kube_node_labels{label_node_role_kubernetes_io_production!=\"true\"}\n  * on (node) group_right\n  kube_node_status_allocatable_cpu_cores\n) by (instance))\n\n\n* 100"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "min(sum(\n  kube_node_labels{label_node_role_kubernetes_io_production!=\"true\"}\n  * on (node) group_right\n  kube_node_status_allocatable_memory_bytes\n) by (instance))",
     "legendFormat": "Allocatable Memory"
    },
    {
     "expr": "min(sum(\n  kube_node_labels{label_node_role_kubernetes_io_production!=\"true\"}\n  * on (node) group_right\n  kube_pod_container_resource_requests_memory_bytes\n) by (instance))",
     "legendFormat": "Requested Memory"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(\n  kube_node_labels{label_node_role_kubernetes_io_production!=\"true\"}\n  * on (node) group_right\n  kube_pod_container_resource_requests_memory_bytes\n) by (instance))\n\n/ \n\nmin(sum(\n  kube_node_labels{label_node_role_kubernetes_io_production!=\"true\"}\n  * on (node) group_right\n  kube_node_status_allocatable_memory_bytes\n) by (instance))\n\n\n* 100"
    }
   ]
  },
  {
   "title": "Cluster Node Utilisation by CPU and RAM requests",
   "type": "table-old",
   "description": "This table shows the comparison of CPU and RAM requests by applications, vs the capacity of the node",
   "gridPos": { "h": 8, "w": 10, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "kube_node_labels{label_node_role_kubernetes_io_production!=\"true\"}\n* on (node)\n( \n  sum(kube_pod_container_resource_requests_cpu_cores) by (node) \n  /\n  sum(kube_node_status_allocatable_cpu_cores) by (node)\n) * 100",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "kube_node_labels{label_node_role_kubernetes_io_production!=\"true\"}\n* on (node)\n( \n  sum(kube_pod_container_resource_requests_memory_bytes) by (node) \n  /\n  sum(kube_node_status_allocatable_memory_bytes) by (node)\n) * 100",
     "legendFormat": "{{ node }}"
    }
   ]
  }
 ]
}