{
 "title": "MySQL Monitor",
 "description": "Basic Mysql dashboard for the prometheus exporter ",
 "tags": [
  "Databases",
  "backgroundservices"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "release", "query": "label_values(mysql_up,release)" }
  ]
 },
 "panels": [
  { "title": "全局状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "实例数",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(mysql_up{release=\"$release\"})"
    }
   ]
  },
  {
   "title": "慢查询数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_slow_queries{release=\"$release\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "主从延迟",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_slave_status_seconds_behind_master",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "总行数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(mysql_info_schema_table_rows{release=\"$release\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "SQL执行频率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_commands_total{command=\"insert\"}[30s])",
     "legendFormat": "插入-{{instance}}"
    },
    {
     "expr": "irate(mysql_global_status_commands_total{command=\"select\"}[30s])",
     "legendFormat": "查询-{{instance}}"
    },
    {
     "expr": "irate(mysql_global_status_commands_total{command=\"update\"}[30s])",
     "legendFormat": "更新-{{instance}}"
    }
   ]
  },
  {
   "title": "网络繁忙度",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_bytes_received{release=\"$release\"}[5m])",
     "legendFormat": "接收-{{instance}}"
    },
    {
     "expr": "irate(mysql_global_status_bytes_sent{release=\"$release\"}[5m])",
     "legendFormat": "发送{{instance}}"
    }
   ]
  },
  { "title": "异常", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "连接异常率",
   "type": "graph",
   "description": "aborted_connects:\n    1、 客户端没有权限但是尝试访问MySQL数据库。\n    2、 客户端输入的密码有误。\n    3、 连接包未包含正确信息。\n   4、 连接时间超过系统变量connect_timeout（默认是10s）\naborted_clients:\n  1. 客户端程序退出前未调用mysql_close()\n  2. 客户端长时间未请求服务端（空闲时间超过wait_timeout或interactive_timeout）。\n  3. 数据传输时客户端程序突然中断",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_aborted_clients{release=\"$release\"}[5m])",
     "legendFormat": "aborted_clients:{{instance}}"
    },
    {
     "expr": "irate(mysql_global_status_aborted_connects{release=\"$release\"}[5m])",
     "legendFormat": "aborted_connects:{{instance}}"
    }
   ]
  },
  { "title": "存储", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "磁盘使用量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(mysql_info_schema_table_size{component=\"data_length\"}/1024/1024) by (instance)",
     "legendFormat": "表:{{instance}}"
    },
    {
     "expr": "sum(mysql_info_schema_table_size{component=\"data_length\"}/1024/1024) by (instance)",
     "legendFormat": "索引:{{instance}}"
    }
   ]
  }
 ]
}