{
 "title": "Node WiFi",
 "description": "Host WiFi statistics provided by the prometheus node_exporter.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_wifi_station_signal_dbm{job=\"node\"}, instance)"
   },
   {
    "name": "port",
    "label": "port",
    "query": "label_values(node_wifi_station_signal_dbm, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "bssid",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "node_wifi_station_info", "legendFormat": "ssid" }
   ]
  },
  {
   "title": "SSID",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "node_wifi_station_info", "legendFormat": "ssid" }
   ]
  },
  {
   "title": "Signal strength",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "expr": "node_wifi_station_signal_dbm{instance=~\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "node_wifi_interface_frequency_hertz{instance=~\"$node:$port\"}",
     "legendFormat": "frequency"
    }
   ]
  },
  {
   "title": "Connected seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_wifi_station_connected_seconds_total{instance=~\"$node:$port\"}",
     "legendFormat": "connected seconds"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_wifi_station_beacon_loss_total{instance=~\"$node:$port\"}[1m])",
     "legendFormat": "beacon loss"
    },
    {
     "expr": "rate(node_wifi_station_transmit_failed_total{instance=~\"$node:$port\"}[1m])",
     "legendFormat": "tx fail"
    },
    {
     "expr": "rate(node_wifi_station_transmit_retries_total{instance=~\"$node:$port\"}[1m])",
     "legendFormat": "tx retries"
    }
   ]
  },
  {
   "title": "Network throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes{instance=~\"$node:$port\",device=\"wlan0\"}[1m])",
     "legendFormat": "rx"
    },
    {
     "expr": "rate(node_network_transmit_bytes{instance=~\"$node:$port\",device=\"wlan0\"}[1m])",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Interface Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "node_wifi_station_transmit_bits_per_second{instance=~\"$node:$port\"}",
     "legendFormat": "transmit"
    },
    {
     "expr": "node_wifi_station_receive_bits_per_second{instance=~\"$node:$port\"}",
     "legendFormat": "receive"
    }
   ]
  }
 ]
}