{
 "title": "Platform API Overview",
 "description": "Platform API dashboard prometheus",
 "tags": [
  "prometheus",
  "api"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(http_request_duration_seconds_count{component=~\"server-api.*\"},release)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,3h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "exclude_route", "label": "Exclude routes", "query": "k8s.*,nothing" },
   {
    "name": "threshold",
    "label": "Threshold",
    "query": "0.1,0.3, 0.5, 0.8, 1.2, 1.6, 2.4, 3.5, 5"
   }
  ]
 },
 "panels": [
  {
   "title": "global stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests by service [$interval]",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{path!~\"/$exclude_route\"}[$interval])) by (release)",
       "legendFormat": "{{ release }}"
      }
     ]
    },
    {
     "title": "Slow requests > $threshold s [$interval]",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 5, "x": 7, "y": 1 },
     "targets": [
      {
       "expr": "(100 - sum(rate(http_request_duration_seconds_bucket{path!~\"/$exclude_route\", le=\"$threshold\"}[$interval])) by (release) / sum(rate(http_request_duration_seconds_count{path!~\"/$exclude_route\"}[$interval])) by (release) * 100) > 5",
       "legendFormat": "{{ release }}"
      }
     ]
    },
    {
     "title": "Return codes over [$interval]",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate(http_request_duration_seconds_count{path!~\"/$exclude_route\"}[$interval])) by (status_code)",
       "legendFormat": " {{status_code}}"
      }
     ]
    },
    {
     "title": "Response time over [$interval]",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_sum{path!~\"/$exclude_route\"}[$interval])) / sum(rate(http_request_duration_seconds_count{path!~\"/$exclude_route\"}[$interval])) * 1000"
      }
     ]
    },
    {
     "title": "Requests over [$interval]",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{path!~\"/$exclude_route\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Error rate 5xx [$interval]",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
     "format": "percentunit",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{path!~\"/$exclude_route\", status_code=~\"5..\"}[$interval])) / sum(rate(http_request_duration_seconds_count{path!~\"/$exclude_route\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Error rate 4xx [$interval]",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
     "format": "percentunit",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{path!~\"/$exclude_route\", status_code=~\"4..\"}[$interval])) / sum(rate(http_request_duration_seconds_count{path!~\"/$exclude_route\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Request duration heatmap over [$interval]",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_bucket{path!~\"/$exclude_route\"}[$interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$service stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests over [$interval]",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Response time over [$interval]",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_sum{release=\"$service\", path!~\"/$exclude_route\"}[$interval])) / sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\"}[$interval])) * 1000"
      }
     ]
    },
    {
     "title": "Error rate 5xx [$interval]",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
     "format": "percentunit",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\", status_code=~\"5..\"}[$interval])) / sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Error rate 4xx [$interval]",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 2 },
     "format": "percentunit",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\", status_code=~\"4..\"}[$interval])) / sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Return codes over [$interval]",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 3, "x": 12, "y": 2 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\"}[$interval])) by (status_code)",
       "legendFormat": " {{status_code}}"
      }
     ]
    },
    {
     "title": "Methods over [$interval]",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 3, "x": 15, "y": 2 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\"}[$interval])) by (method)",
       "legendFormat": " {{method}}"
      }
     ]
    },
    {
     "title": "Request by route [$interval]",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 2 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\"}[$interval])) by (path)",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Request duration heatmap over [$interval]",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_bucket{release=\"$service\", path!~\"/$exclude_route\"}[$interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response duration over [$interval]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_sum{release=\"$service\", path!~\"/$exclude_route\"}[$interval])) / sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\"}[$interval])) * 1000"
      }
     ]
    },
    {
     "title": "Total requests over [$interval]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\"}[$interval]))",
       "legendFormat": "Total requests $service"
      }
     ]
    },
    {
     "title": "Status codes over [$interval]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\"}[$interval])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "Method over [$interval]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\"}[$interval])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  { "title": "$service route stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Slow routes > $threshold s [$interval]",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "(100 - sum(rate(http_request_duration_seconds_bucket{release=\"$service\", path!~\"/$exclude_route\", le=\"$threshold\"}[$interval])) by (path) / sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\"}[$interval])) by (path) * 100) > 5",
     "legendFormat": "{{ path}}"
    }
   ]
  },
  {
   "title": "Slow route with method > $threshold s [$interval]",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "(100 - sum(rate(http_request_duration_seconds_bucket{release=\"$service\", path!~\"/$exclude_route\", le=\"$threshold\"}[$interval])) by (path, method) / sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\"}[$interval])) by (path, method) * 100) > 5",
     "legendFormat": "{{method}} {{ path}}"
    }
   ]
  },
  {
   "title": "Slow route with method and status > $threshold s [$interval]",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 3 },
   "targets": [
    {
     "expr": "(100 - sum(rate(http_request_duration_seconds_bucket{release=\"$service\", path!~\"/$exclude_route\", le=\"$threshold\"}[$interval])) by (path, method, status_code) / sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\"}[$interval])) by (path, method, status_code) * 100) > 5",
     "legendFormat": "{{method}} {{status_code}} {{ path}}"
    }
   ]
  },
  {
   "title": "Response duration over [$interval]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{release=\"$service\", path!~\"/$exclude_route\"}[$interval])) by(path) / sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\"}[$interval])) by (path) * 1000",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latency of 90% requests over [$interval]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{release=\"$service\", path!~\"/$exclude_route\"}[$interval])) by (le, path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "$service status codes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "2XX over [$interval]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\", status_code=~\"2..\"}[$interval])) by (method)",
       "legendFormat": "{{method}} "
      }
     ]
    },
    {
     "title": "3XX over [$interval]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\", status_code=~\"3..\"}[$interval])) by (method)",
       "legendFormat": "{{method}} "
      }
     ]
    },
    {
     "title": "4XX over [$interval]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\", status_code=~\"4..\"}[$interval])) by (method)",
       "legendFormat": "{{method}} "
      }
     ]
    },
    {
     "title": "5XX over [$interval]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\", status_code=~\"5..\"}[$interval])) by (method)",
       "legendFormat": "{{method}} "
      }
     ]
    },
    {
     "title": "1XX over [$interval]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\", status_code=~\"1..\"}[$interval])) by (method)",
       "legendFormat": "{{method}} "
      }
     ]
    }
   ]
  },
  {
   "title": "$service methods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "GET over [$interval]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\", method=\"GET\"}[$interval])) by (status_code)",
       "legendFormat": "{{status_code}} "
      }
     ]
    },
    {
     "title": "POST over [$interval]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\", method=\"POST\"}[$interval])) by (status_code)",
       "legendFormat": "{{status_code}} "
      }
     ]
    },
    {
     "title": "PUT over [$interval]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\", method=\"PUT\"}[$interval])) by (status_code)",
       "legendFormat": "{{status_code}} "
      }
     ]
    },
    {
     "title": "DELETE over [$interval]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\", method=\"DELETE\"}[$interval])) by (status_code)",
       "legendFormat": "{{status_code}} "
      }
     ]
    },
    {
     "title": "HEAD over [$interval]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\", method=\"HEAD\"}[$interval])) by (status_code)",
       "legendFormat": "{{status_code}} "
      }
     ]
    },
    {
     "title": "OPTIONS over [$interval]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\", method=\"OPTIONS\"}[$interval])) by (status_code)",
       "legendFormat": "{{status_code}} "
      }
     ]
    },
    {
     "title": "TRACE over [$interval]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\", method=\"TRACE\"}[$interval])) by (status_code)",
       "legendFormat": "{{status_code}} "
      }
     ]
    },
    {
     "title": "CONNECT over [$interval]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\", method=\"CONNECT\"}[$interval])) by (status_code)",
       "legendFormat": "{{status_code}} "
      }
     ]
    },
    {
     "title": "PATCH over [$interval]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{release=\"$service\", path!~\"/$exclude_route\", method=\"PATCH\"}[$interval])) by (status_code)",
       "legendFormat": "{{status_code}} "
      }
     ]
    }
   ]
  }
 ]
}