{
 "title": "Scan Monitoring",
 "description": "Scanning monitor",
 "time": { "from": "2019-05-15T11:18:19.884Z", "to": "2019-05-15T11:56:01.953Z" },
 "panels": [
  {
   "title": "Memory by Service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_working_set_bytes{namespace=\"default\",pod_name!~\"^filebeat.*|^prometheus.*|^kibana.*|^logstash.*\",container_name!=\"POD\"}[5m])) by (image)"
    }
   ]
  },
  {
   "title": "CPU Pods ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{namespace=\"default\",container_name!~\"POD|^filebeat.*|grafana|kibana|automation|^logstash.*|^prometheus.*\",name=~\"^k8s.*\"}[5m])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Use All pods",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_working_set_bytes{namespace=\"default\",pod_name!~\"^filebeat.*|^prometheus.*|^kibana.*|^logstash.*\",container_name!=\"POD\"}[5m])) by (pod_name)"
    }
   ]
  }
 ]
}