{
 "title": "Servers Performance Monitoring(TCP Connections)",
 "description": "Basic overview of windows host metrics, based on WMI Exporter (v0.15.0)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(windows_os_time, job)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(windows_iis_worker_threads{job=~\"$server.*\"}, app)"
   },
   {
    "name": "host",
    "label": "Hostname",
    "query": "label_values(windows_os_time{job=~\"$job\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "TCP  Connections Active ",
   "type": "graph",
   "description": "It shows the active TCP connections installed on the server instantly.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(windows_tcp_connections_active{instance=~\"$host\"}[5m])",
     "legendFormat": " {{instance}}: {{process}}:"
    }
   ]
  },
  {
   "title": "TCP Connection Failures",
   "type": "graph",
   "description": "It shows the number of instant errors received in TCP connections.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(windows_tcp_connection_failures{instance=~\"$host\"}[5m])",
     "legendFormat": " {{instance}}: {{process}}:"
    }
   ]
  },
  {
   "title": "TCP Connections Established",
   "type": "graph",
   "description": "After the connection is established, it shows the instant number of data transfer.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(windows_tcp_connections_established{instance=~\"$host\"}[5m])",
     "legendFormat": " {{instance}}: {{process}}:"
    }
   ]
  },
  {
   "title": "TCP Connections Passive",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(windows_tcp_connections_passive{instance=~\"$host\"}[5m])",
     "legendFormat": " {{instance}}: {{process}}:"
    }
   ]
  }
 ]
}