{
 "title": "Servers Inventory",
 "description": "The dashboards allows to see amount of monitored servers. Instances are sorted by memory size and CPU Cores.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({__name__=~\"node_load1|process_start_time_seconds\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Distribution by Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Amount of Servers",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 0 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 1)",
     "legendFormat": "1G"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 1 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 2)",
     "legendFormat": "2Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 2 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 3)",
     "legendFormat": "3Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 3 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 4)",
     "legendFormat": "4Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 4 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 5)",
     "legendFormat": "5Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 5 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 6)",
     "legendFormat": "6Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 6 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 7)",
     "legendFormat": "7Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 7 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 8)",
     "legendFormat": "8Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 8 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 9)",
     "legendFormat": "9Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 9 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 10)",
     "legendFormat": "10Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 10 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 11)",
     "legendFormat": "11Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 11 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 12)",
     "legendFormat": "12Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 12 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 13)",
     "legendFormat": "13Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 13 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 14)",
     "legendFormat": "14Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 14 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 15)",
     "legendFormat": "15Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 15 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 16)",
     "legendFormat": "16Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 16 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 17)",
     "legendFormat": "17Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 17 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 18)",
     "legendFormat": "18Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 18 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 19)",
     "legendFormat": "19Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 19 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 20)",
     "legendFormat": "20Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 20 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 21)",
     "legendFormat": "21Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 21 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 22)",
     "legendFormat": "22Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 22 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 23)",
     "legendFormat": "23Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 23 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 24)",
     "legendFormat": "24Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 24 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 25)",
     "legendFormat": "25Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 25 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 26)",
     "legendFormat": "26Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 26 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 27)",
     "legendFormat": "27Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 27 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 28)",
     "legendFormat": "28Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 28 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 29)",
     "legendFormat": "29Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 29 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 30)",
     "legendFormat": "30Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 30 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 31)",
     "legendFormat": "31Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 31 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 32)",
     "legendFormat": "32Gb"
    },
    {
     "expr": "count(node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 > 32 and node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024 < 64)",
     "legendFormat": "64Gb"
    }
   ]
  },
  {
   "title": "Metric series over time (Gb)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$host\"}/1024/1024/1024",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$host\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Distribution by CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Cores",
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "count((count by(instance) (node_cpu{instance=~\"$host\",mode=~\"user\"}) or sum by (instance) (rdsosmetrics_General_numVCPUs{instance=~\"$host\"} or up * 0)) < 2)",
       "legendFormat": "1 Core"
      },
      {
       "expr": "count( \n(count by(instance) (node_cpu{instance=~\"$host\",mode=~\"user\"}) or sum by (instance) (rdsosmetrics_General_numVCPUs{instance=~\"$host\"} or up * 0)) > 1\nand \n(count by(instance) (node_cpu{instance=~\"$host\",mode=~\"user\"}) or sum by (instance) (rdsosmetrics_General_numVCPUs{instance=~\"$host\"} or up * 0)) < 3\n)",
       "legendFormat": "2 Cores"
      },
      {
       "expr": "count( \n(count by(instance) (node_cpu{instance=~\"$host\",mode=~\"user\"}) or sum by (instance) (rdsosmetrics_General_numVCPUs{instance=~\"$host\"} or up * 0)) > 3\nand \n(count by(instance) (node_cpu{instance=~\"$host\",mode=~\"user\"}) or sum by (instance) (rdsosmetrics_General_numVCPUs{instance=~\"$host\"} or up * 0)) < 5\n)",
       "legendFormat": "4 Cores"
      },
      {
       "expr": "count( \n(count by(instance) (node_cpu{instance=~\"$host\",mode=~\"user\"}) or sum by (instance) (rdsosmetrics_General_numVCPUs{instance=~\"$host\"} or up * 0)) > 4\nand \n(count by(instance) (node_cpu{instance=~\"$host\",mode=~\"user\"}) or sum by (instance) (rdsosmetrics_General_numVCPUs{instance=~\"$host\"} or up * 0)) < 9\n)",
       "legendFormat": "8 Cores"
      }
     ]
    },
    {
     "title": "Metric series over time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "(count by(instance) (node_cpu{instance=~\"$host\",mode=~\"user\"}) or sum by (instance) (rdsosmetrics_General_numVCPUs{instance=~\"$host\"} or up * 0)) > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "count by(instance) (node_cpu{instance=~\"$host\",mode=~\"user\"}) or sum by (instance) (rdsosmetrics_General_numVCPUs{instance=~\"$host\"} or up * 0)"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "(count by(instance) (node_cpu{instance=~\"$host\",mode=~\"user\"}) or sum by (instance) (rdsosmetrics_General_numVCPUs{instance=~\"$host\"} or up * 0)) > 0 "
      }
     ]
    }
   ]
  }
 ]
}