{
 "title": "SFTP",
 "description": "Dashboard for Prometheus sftp-exporter",
 "tags": [ "sftp" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "path",
    "query": {
     "query": "label_values(sftp_objects_available, path)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "description": "Status of SFTP connection",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sftp_up" }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "description": "Status of SFTP connection",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "sftp_up" }
   ]
  },
  {
   "title": "Objects Available - ${path}",
   "type": "singlestat",
   "description": "Number of objects in the path",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "repeat": "path",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sftp_objects_available{path=\"$path\"}"
    }
   ]
  },
  {
   "title": "Objects Total Size - ${path}",
   "type": "singlestat",
   "description": "Total size of all the objects in the path",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "repeat": "path",
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sftp_objects_total_size_bytes{path=\"$path\"}"
    }
   ]
  },
  {
   "title": "Filesystem Usage - ${path}",
   "type": "gauge",
   "description": "Usage for filesystem containing ${path}",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "repeat": "path",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sftp_filesystem_total_space_bytes{path=\"$path\"} - sftp_filesystem_free_space_bytes{path=\"$path\"})/sftp_filesystem_total_space_bytes{path=\"$path\"}) *100"
    }
   ]
  },
  {
   "title": "Objects Available",
   "type": "graph",
   "description": "Number of objects available in each path",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sftp_objects_available", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "Objects Total Size",
   "type": "graph",
   "description": "Total size of all the objects in each path",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "sftp_objects_total_size_bytes", "legendFormat": "{{path}}" }
   ]
  }
 ]
}