{
 "title": "Budget Smart Home Overview",
 "description": "The dashboard to accompany the blog series at www.budgetsmarthome.co.uk",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Inbound Data",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (country, city, latitude, longitude) (count_over_time({job=\"fluentbit\"}|= \"pppoe0\" | json | latitude != \"\" and latitude != 0 and longitude != \"\" and longitude != 0 [$__interval]))"
    }
   ]
  },
  {
   "title": "Most Targeted Ports",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "topk(5,sum(count_over_time({job=\"fluentbit\"}|= \"pppoe0\" | json | dest_port != \"\"[${__interval}])) by (dest_port))",
     "legendFormat": "{{dest_port}}"
    }
   ]
  },
  {
   "title": "Busiest IP Addresses",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(rate({job=\"fluentbit\"}|= \"pppoe0\" | json | latitude != \"\" and latitude != 0 and longitude != \"\" and longitude != 0 [$__interval])) by (country, city, latitude, longitude, source))",
     "legendFormat": "{{ source }} ( {{ city }} - {{ country }} )"
    }
   ]
  },
  {
   "title": "Active Pi-Hole Servers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pihole_status)", "legendFormat": "{{ legend }}" }
   ]
  },
  {
   "title": "% ads blocked",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pihole_ads_percentage_today", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "Current Conected Users",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unifipoller_site_users{subsystem=\"lan\",job=\"unifipoller\", site_name=\"27Maddox (default)\"}"
    }
   ]
  },
  {
   "title": "Broadband Speeds",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unifipoller_device_speedtest_download",
     "legendFormat": "DOWN"
    },
    {
     "expr": "unifipoller_device_speedtest_upload",
     "legendFormat": "UP"
    }
   ]
  },
  {
   "title": "Dropped Packets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"fluentbit\"} |= \"pppoe0\" | json | accept_or_drop = \"D\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Unique IP Addresses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum  by (source) (count_over_time({job=\"fluentbit\"} |= \"pppoe0\" | json | accept_or_drop = \"D\" [${__interval}])))"
    }
   ]
  },
  {
   "title": "Package Updates Required",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pacman_updates_pending" }
   ]
  },
  {
   "title": "Unique domains",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(pihole_unique_domains)/count(pihole_status)"
    }
   ]
  },
  {
   "title": "WiFi Client Satisfaction",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(unifipoller_client_satisfaction_ratio)/count(unifipoller_client_satisfaction_ratio)) by (site_name)"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unifipoller_device_speedtest_download",
     "legendFormat": "DOWN"
    },
    {
     "expr": "unifipoller_device_speedtest_upload",
     "legendFormat": "UP"
    }
   ]
  },
  {
   "title": "Domains being blocked",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(pihole_domains_being_blocked)/count(pihole_status)"
    }
   ]
  },
  {
   "title": "UPS Power Load",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apcupsd_ups_load_percent" }
   ]
  }
 ]
}