{
 "title": "Sport Feed Overview",
 "description": "Sport feed data processing overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "feed_instance",
    "label": "Feed instance",
    "query": "label_values(jvm_info{component=\"sport-feed\"},kubernetes_pod_name)"
   },
   {
    "name": "thread_pool",
    "label": "Pool",
    "query": "label_values(thread_pool_execute_duration_seconds_count{kubernetes_pod_name=\"$feed_instance\"},pool_name)"
   },
   {
    "name": "task_type",
    "label": "Task",
    "query": "label_values(thread_pool_execute_duration_seconds_count{kubernetes_pod_name=\"$feed_instance\", pool_name=~\"$thread_pool\"}, task_type)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,3h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Feed messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages over [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(feed_messages_total{kubernetes_pod_name=\"$feed_instance\"}[$interval])) by(message_type)",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "Processing of 90% messages over [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(thread_pool_execute_duration_seconds_bucket{kubernetes_pod_name=\"$feed_instance\"}[$interval])) by (le, task_type))",
     "legendFormat": "{{task_type}}"
    }
   ]
  },
  {
   "title": "Live messages rate [$interval]",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 15 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(feed_messages_total{kubernetes_pod_name=\"$feed_instance\", message_interest=\"live\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Live messages kind over [$interval]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 9, "x": 5, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(feed_messages_total{kubernetes_pod_name=\"$feed_instance\", message_interest=\"live\"}[$interval])) by (message_type)",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "Live messages count over [$interval]",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 15 },
   "targets": [
    {
     "expr": "sum(increase(feed_messages_total{kubernetes_pod_name=\"$feed_instance\", message_interest=\"live\"}[$interval])) by(message_type)",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "Prematch messages rate [$interval]",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 21 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(feed_messages_total{kubernetes_pod_name=\"$feed_instance\", message_interest=\"prematch\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Prematch messages kind over [$interval]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 9, "x": 5, "y": 21 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(feed_messages_total{kubernetes_pod_name=\"$feed_instance\", message_interest=\"prematch\"}[$interval])) by (message_type)",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "Prematch messages count over [$interval]",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 21 },
   "targets": [
    {
     "expr": "sum(increase(feed_messages_total{kubernetes_pod_name=\"$feed_instance\", message_interest=\"prematch\"}[$interval])) by (message_type)",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  { "title": "Thread Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Thread pool \"$thread_pool\" execute heatmap over [$interval]",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(thread_pool_execute_duration_seconds_bucket{kubernetes_pod_name=\"$feed_instance\", pool_name=~\"$thread_pool\", task_type=~\"$task_type\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Thread pool \"$thread_pool\" wait heatmap over [$interval]",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(thread_pool_wait_duration_seconds_bucket{kubernetes_pod_name=\"$feed_instance\", pool_name=~\"$thread_pool\", task_type=~\"$task_type\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processing of 90% messages over [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(thread_pool_execute_duration_seconds_bucket{kubernetes_pod_name=\"$feed_instance\"}[$interval])) by (le, pool_name))",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Threads by pool",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "avg(thread_pool_pool_size{kubernetes_pod_name=\"$feed_instance\"}) by (pool_name)",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Active threads per pool",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 42 },
   "targets": [
    {
     "expr": "avg(thread_pool_active_threads{kubernetes_pod_name=\"$feed_instance\"})by (pool_name)",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Queued tasks per pool",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "avg(thread_pool_queued_size{kubernetes_pod_name=\"$feed_instance\"}) by (pool_name)",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Errored tasks over [$interval]",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 47 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(thread_pool_fail_tasks_total{kubernetes_pod_name=\"$feed_instance\"}[$interval])) by (pool_name)",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Completed tasks over [$interval]",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 5, "y": 47 },
   "targets": [
    {
     "expr": "sum(increase(thread_pool_complete_tasks_total{kubernetes_pod_name=\"$feed_instance\"}[$interval])) by (pool_name)",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  { "title": "Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Threads",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 53 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_threads_current{kubernetes_pod_name=\"$feed_instance\"})"
    }
   ]
  },
  {
   "title": "Threads peak",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 53 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_threads_peak{kubernetes_pod_name=\"$feed_instance\"})"
    }
   ]
  },
  {
   "title": "Deamon threads",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 53 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_threads_daemon{kubernetes_pod_name=\"$feed_instance\"})"
    }
   ]
  },
  {
   "title": "Deadlock threads",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 53 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_threads_deadlocked{kubernetes_pod_name=\"$feed_instance\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "eagle_pod_container_resource_usage_cpu_cores{pod=\"$feed_instance\"} / eagle_pod_container_resource_limits_cpu_cores{pod=\"$feed_instance\"} * 100",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "eagle_pod_container_resource_usage_memory_bytes{pod=\"$feed_instance\"}",
     "legendFormat": " used"
    },
    {
     "expr": "eagle_pod_container_resource_limits_memory_bytes{pod=\"$feed_instance\"}",
     "legendFormat": " limit"
    }
   ]
  },
  {
   "title": "JVM memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{kubernetes_pod_name=\"$feed_instance\"}",
     "legendFormat": " {{area}} commited"
    },
    {
     "expr": "jvm_memory_bytes_used{kubernetes_pod_name=\"$feed_instance\"}",
     "legendFormat": " {{area}} used"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{kubernetes_pod_name=\"$feed_instance\"})",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}