{
 "title": "SSL Monitoring",
 "description": "Monitor SSL certificates in Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Domain",
    "query": "label_values(security_ssl_mozilla_observatory{job=\"all_hosts_ssl_stats\"}, url)"
   }
  ]
 },
 "panels": [
  { "title": "SSL cert days remaining", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$Domain",
   "type": "singlestat",
   "description": "The amount of days, the SSL certificate is still valid.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "repeat": "Domain",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(security_ssl_expire_days_remaining{job=\"all_hosts_ssl_stats\", url=~\"$Domain\"})"
    }
   ]
  },
  {
   "title": "HTTP Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Domain",
     "type": "singlestat",
     "description": "Ok for all HTTP status codes between 200 and 299 (inclusive)",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
     "repeat": "Domain",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(security_ssl_details{job=\"all_hosts_ssl_stats\", url=~\"$Domain\"})"
      }
     ]
    },
    {
     "title": "$Domain",
     "type": "singlestat",
     "description": "Ok for all HTTP status codes between 200 and 299 (inclusive)",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(security_ssl_details{job=\"all_hosts_ssl_stats\", url=~\"$Domain\"})"
      }
     ]
    },
    {
     "title": "$Domain",
     "type": "singlestat",
     "description": "Ok for all HTTP status codes between 200 and 299 (inclusive)",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(security_ssl_details{job=\"all_hosts_ssl_stats\", url=~\"$Domain\"})"
      }
     ]
    },
    {
     "title": "$Domain",
     "type": "singlestat",
     "description": "Ok for all HTTP status codes between 200 and 299 (inclusive)",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(security_ssl_details{job=\"all_hosts_ssl_stats\", url=~\"$Domain\"})"
      }
     ]
    },
    {
     "title": "$Domain",
     "type": "singlestat",
     "description": "Ok for all HTTP status codes between 200 and 299 (inclusive)",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(security_ssl_details{job=\"all_hosts_ssl_stats\", url=~\"$Domain\"})"
      }
     ]
    },
    {
     "title": "$Domain",
     "type": "singlestat",
     "description": "Ok for all HTTP status codes between 200 and 299 (inclusive)",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(security_ssl_details{job=\"all_hosts_ssl_stats\", url=~\"$Domain\"})"
      }
     ]
    },
    {
     "title": "$Domain",
     "type": "singlestat",
     "description": "Ok for all HTTP status codes between 200 and 299 (inclusive)",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(security_ssl_details{job=\"all_hosts_ssl_stats\", url=~\"$Domain\"})"
      }
     ]
    },
    {
     "title": "$Domain",
     "type": "singlestat",
     "description": "Ok for all HTTP status codes between 200 and 299 (inclusive)",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(security_ssl_details{job=\"all_hosts_ssl_stats\", url=~\"$Domain\"})"
      }
     ]
    }
   ]
  },
  { "title": "SSL Score", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "$Domain",
   "type": "singlestat",
   "description": "Detailed Mozilla SSL scoring: https://observatory.mozilla.org/analyze/$Domain",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "repeat": "Domain",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(security_ssl_mozilla_observatory{job=\"all_hosts_ssl_stats\", url=~\"$Domain\"})"
    }
   ]
  },
  { "title": "Overall Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Mozilla SSL Score",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(security_ssl_mozilla_observatory{job=\"all_hosts_ssl_stats\"}) by (url)",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "SSL Remaining Days",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(security_ssl_expire_days_remaining{job=\"all_hosts_ssl_stats\"}) by (url)",
     "legendFormat": "{{url}}"
    }
   ]
  }
 ]
}