{
 "title": "TheGeekFreaks Unraid Dashboard 1.6",
 "description": "Developed byTheGeekFreaks",
 "tags": [
  "UNRAID",
  "Telegraf",
  "InfluxDB",
  "opnsense",
  "pfsense",
  "usv",
  "ups",
  "network",
  "security",
  "sensei",
  "firwall",
  "map",
  "geoip",
  "worldmap",
  "TheGeekFreaks",
  "tgf"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   { "name": "Datasource_Telegraf", "label": "Telegraf Datasource", "query": "influxdb" },
   {
    "name": "CPU_Threads",
    "label": "CPU Threads",
    "query": "SELECT last(\"n_cpus\") AS \"mean_n_cpus\" FROM \"system\"  WHERE (\"host\" =~ /^$Host$/) "
   },
   { "name": "UPS_Max_Watts", "label": "UPS Max Output (Watts)", "query": "600" },
   {
    "name": "Drives_Flash",
    "label": "Flash (Boot) Drive",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"ID_SERIAL\""
   },
   {
    "name": "Drives_Cache",
    "label": "Cache Drive(s)",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"ID_SERIAL\""
   },
   {
    "name": "Drives_Parity",
    "label": "Parity Drive(s)",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"ID_SERIAL\""
   },
   {
    "name": "Drives_Array",
    "label": "Array Drive(s)",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"ID_SERIAL\""
   },
   {
    "name": "Drives_Unassigned",
    "label": "Unassigned Drive(s)",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"ID_SERIAL\""
   },
   { "name": "Path_Unassigned", "label": "Unassigned Drive Path", "query": "/mnt/disks/Unassigned" },
   { "name": "telegrafdatasource", "label": "Telegraf Datasource", "query": "influxdb" },
   {
    "name": "cpucores",
    "label": "CPU Threads",
    "query": "SELECT mean(\"n_cpus\") AS \"mean_n_cpus\" FROM \"system\"  WHERE (\"host\" =~ /^$host$/) "
   },
   {
    "name": "cachedevice",
    "label": "Cache Devices (diskio)",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\""
   },
   { "name": "interval", "label": "Interval", "query": "5" },
   { "name": "diskdatasource", "label": "Disk Datasource", "query": "influxdb" },
   { "name": "currency", "label": "Currency", "query": "$,€,£,C$,kr,₽,¥" },
   { "name": "kwhprice", "label": "kWh Price", "query": "0.28" },
   { "name": "dataSource", "query": "influxdb" },
   {
    "name": "Host2",
    "label": "pfsense",
    "query": "SHOW TAG VALUES FROM \"pf\" WITH KEY = \"host\""
   },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   {
    "name": "Interface",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE \"host\" =~ /^$server$/"
   },
   { "name": "endpoint", "label": "Endpoint", "query": "worldping.*" },
   { "name": "probe", "label": "Probe(s)", "query": "worldping.$endpoint.*" },
   { "name": "outliers", "label": "Outliers", "query": "100,99.9,99.5,99,95,50" },
   {
    "name": "check_type",
    "label": "Check Type",
    "query": {
     "query": "label_values(sm_check_info, check_name)"
    }
   },
   {
    "name": "region",
    "query": {
     "query": "label_values(sm_check_info, region)"
    }
   },
   { "name": "_DS_SM_LOGS", "query": "${VAR__DS_SM_LOGS}" },
   { "name": "Drives_Cach" }
  ]
 },
 "panels": [
  {
   "title": "FIREWALL ERLAUBT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "event.action",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "event.action.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "pfelk*  AND event.action:pass",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 10, "x": 7, "y": 0 },
   "options": {
    "content": "<img src=\"https://cdn.thegeekfreaks.de/Download/Logo_v2.png\" >\n         "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FIREWALL GEBLOCKT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "event.action",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "event.action.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "pfelk* AND event.action:block",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "VERBINDUNG: QUELLENLÄNDER",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:710",
       "fake": true,
       "field": "source.geo.country_name",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:600",
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:701", "field": "select field", "id": "4", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "VERBINDUNG: ZIELLÄNDER",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:710",
       "fake": true,
       "field": "destination.geo.country_name",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:600",
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:701", "field": "select field", "id": "4", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Server Hardware",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "cacheDurationSeconds": 300,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "fields": [
      { "jsonPath": "$.['serverDetails'].title", "name": "" },
      {
       "jsonPath": "$.['serverDetails'].motherboard",
       "name": ""
      },
      { "jsonPath": "$.['serverDetails'].cpu", "name": "" },
      { "jsonPath": "$.['serverDetails'].memory", "name": "" }
     ],
     "method": "GET",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "CPU TEMPERATUR",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 11 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "feature", "operator": "=", "value": "tccd1" }
     ]
    }
   ]
  },
  {
   "title": "UNRAID PROZESSORAUSLASTUNG PRO THREAD",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 18, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "!~", "value": "/^cpu-total/" }
     ]
    }
   ]
  },
  {
   "title": "USV LAST",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Watts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ups_status",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DURCHSCHNITTLICHE USV LAST",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Watts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "INTERFACE NUTZUNG IN %",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:862",
       "fake": true,
       "field": "interface.alias",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:710",
       "fake": true,
       "field": "@timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:701", "field": "select field", "id": "4", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "KARTE DER VERBINDUNGSQUELLEN ",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 14, "x": 5, "y": 18 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3255",
       "field": "source.geo.location",
       "id": "2",
       "settings": { "precision": 4 },
       "type": "geohash_grid"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:3135",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "FIREWALL PRO INTERFACE IN %",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 5, "x": 19, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:862",
       "fake": true,
       "field": "event.action",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:76",
       "fake": true,
       "field": "interface.alias",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:710",
       "fake": true,
       "field": "@timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:701", "field": "select field", "id": "4", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "TRENNER",
   "type": "mxswat-separator-panel",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PARITÄTSSTATUS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$.['serverDetails'].arrayProtection",
       "name": ""
      }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "ARRAY SPEICHER KOMPLETTANSICHT",
   "type": "stat",
   "description": "Note: Change Path to \"mnt/user\" if Cache Drive is Not Present",
   "gridPos": { "h": 4, "w": 14, "x": 2, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Disk 1",
     "groupBy": [
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "fstype" ], "type": "tag" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000000" ], "type": "math" },
       { "params": [ "Used" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000000" ], "type": "math" },
       { "params": [ "Free" ], "type": "alias" }
      ],
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000000" ], "type": "math" },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Used %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/user" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "ARRAY / WOCHE",
   "type": "stat",
   "description": "Note: Query Options >  Min Interval - Must Match on Week/Month/Year To Stay In Sync (Set to 2 Hours by Default For Performance Reasons) - Change Path to \"mnt/user\" if Cache Drive is Not Present",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "Array Growth (Week)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"used\") FROM \"disk\" WHERE (\"path\" = '/mnt/user') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/user0" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "ARRAY / MONAT",
   "type": "stat",
   "description": "Note: Query Options >  Min Interval - Must Match on Week/Month/Year To Stay In Sync (Set to 2 Hours by Default For Performance Reasons) - Change Path to \"mnt/user\" if Cache Drive is Not Present",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "Array Growth (Month)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"used\") FROM \"disk\" WHERE (\"path\" = '/mnt/user') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/user0" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "PARITÄTSCHECK LÄUFT?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$.['serverDetails'].parityCheckRunning",
       "name": ""
      }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "CPU LAST",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 2, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAUFENDE DOCKER",
   "type": "dalvany-image-panel",
   "gridPos": { "h": 4, "w": 14, "x": 2, "y": 36 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$.['docker']['details']['containers'][?(@.status== 'started')].imageUrl",
       "name": ""
      },
      {
       "jsonPath": "$.['docker']['details']['containers'][?(@.status== 'started')].name",
       "name": ""
      }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "GESTARTETE VMs",
   "type": "dalvany-image-panel",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 36 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$.['vm']['details'][?(@.status== 'started')].icon",
       "name": ""
      },
      {
       "jsonPath": "$.['vm']['details'][?(@.status== 'started')].name",
       "name": ""
      }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 2, "x": 22, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RAM Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "DOCKER CPU AUSLASTUNG",
   "type": "graph",
   "description": "Note: Uses Variable",
   "gridPos": { "h": 7, "w": 10, "x": 2, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / $CPU_Threads" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "VM DETAILS",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregation": "Last",
     "cacheDurationSeconds": 300,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "fields": [
      { "jsonPath": "$.['vm']['details'][*].name", "name": "" },
      { "jsonPath": "$.['vm']['details'][*].status", "name": "" },
      {
       "jsonPath": "$.['vm']['details'][*].edit.template_name",
       "name": ""
      },
      {
       "jsonPath": "$.['vm']['details'][*].coreCount",
       "name": ""
      },
      {
       "jsonPath": "$.['vm']['details'][*].ramAllocation",
       "name": ""
      },
      {
       "jsonPath": "$.['vm']['details'][*].primaryGPU",
       "name": ""
      },
      {
       "jsonPath": "$.['vm']['details'][*].hddAllocation.all.[?(@.interface== 'VirtIO')].used",
       "name": ""
      },
      {
       "jsonPath": "$.['vm']['details'][*].hddAllocation.all.[?(@.interface== 'VirtIO')].path",
       "name": ""
      }
     ],
     "method": "GET",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "DOCKER RAMVERBRAUCH",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 2, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "SSD SCHREIBZUGRIFFE (MONAT)",
   "type": "graph",
   "description": "Shows Data Written Per Day\nLast 365 Days",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_ID_SERIAL",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ID_SERIAL" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CACHE GENUTZT %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Cache Utilized %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"used\") AS \"Used\", last(\"free\") AS \"Free\", last(\"total\") AS \"Total\" FROM \"disk\" WHERE (\"path\" = '/rootfs/mnt/user0' AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY \"path\"",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/cache" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "MOVER LÄUFT?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$.['serverDetails'].moverRunning",
       "name": ""
      }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "ARRAY STATUS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$.['serverDetails'].arrayStatus",
       "name": ""
      }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "ZFS SPEICHER KOMPLETTANSICHT",
   "type": "stat",
   "description": "Note: Change Path to \"mnt/user\" if Cache Drive is Not Present",
   "gridPos": { "h": 4, "w": 14, "x": 2, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Disk 1",
     "groupBy": [
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "fstype" ], "type": "tag" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000000" ], "type": "math" },
       { "params": [ "Used" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000000" ], "type": "math" },
       { "params": [ "Free" ], "type": "alias" }
      ],
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000000000" ], "type": "math" },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Used %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/TGFFAST" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "ZFS / WOCHE",
   "type": "stat",
   "description": "Note: Query Options >  Min Interval - Must Match on Week/Month/Year To Stay In Sync (Set to 2 Hours by Default For Performance Reasons) - Change Path to \"mnt/user\" if Cache Drive is Not Present",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "Array Growth (Week)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"used\") FROM \"disk\" WHERE (\"path\" = '/mnt/user') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/TGFFAST" }
     ]
    }
   ]
  },
  {
   "title": "ZFS / MONAT",
   "type": "stat",
   "description": "Note: Query Options >  Min Interval - Must Match on Week/Month/Year To Stay In Sync (Set to 2 Hours by Default For Performance Reasons) - Change Path to \"mnt/user\" if Cache Drive is Not Present",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "Array Growth (Month)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"used\") FROM \"disk\" WHERE (\"path\" = '/mnt/user') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/TGFFAST" }
     ]
    }
   ]
  },
  {
   "title": "WACHSTUM (JAHR)",
   "type": "stat",
   "description": "Note: Query Options >  Min Interval - Must Match on Week/Month/Year To Stay In Sync (Set to 2 Hours by Default For Performance Reasons) - Change Path to \"mnt/user\" if Cache Drive is Not Present",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "Array Growth (Year)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"used\") FROM \"disk\" WHERE (\"path\" = '/mnt/user') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/user0" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "TRENNER",
   "type": "mxswat-separator-panel",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {}
   ]
  },
  {
   "title": "40GBe SERVER ZU PC",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Sende",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eth2" }
     ]
    },
    {
     "alias": "Empfange",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_derivative(last(\"bytes_recv\"), 1s) FROM \"net\" WHERE (\"host\" =~ /^$host$/ AND \"interface\" = 'eth0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eth2" }
     ]
    }
   ]
  },
  {
   "title": "GESAMMT TRAFFIC",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "DOWNLOAD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_recv\"), 1s) FROM \"net\" WHERE (\"interface\" = 'pppoe1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "pppoe1" }
     ]
    }
   ]
  },
  {
   "title": "DOCKER TRAFFIC",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "DOWNLOAD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_recv\"), 1s) *8 FROM \"net\" WHERE (\"interface\" = 'wg0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "br0" }
     ]
    }
   ]
  },
  {
   "title": "40GBe SERVER NETZWERK",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Sende",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_derivative(last(\"bytes_sent\"), 1s) FROM \"net\" WHERE (\"interface\" = 'bond0') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "bond0" }
     ]
    },
    {
     "alias": "Empfange",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_derivative(last(\"bytes_recv\"), 1s) FROM \"net\" WHERE (\"interface\" = 'bond0') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "bond0" }
     ]
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "UPLOAD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_sent\"), 1s) *8 FROM \"net\" WHERE (\"interface\" = 'br0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "br0" }
     ]
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "UPLOAD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_sent\"), 1s) FROM \"net\" WHERE (\"interface\" = 'pppoe1') AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "pppoe1" }
     ]
    }
   ]
  },
  {
   "title": "TRENNER",
   "type": "mxswat-separator-panel",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {}
   ]
  },
  {
   "title": "VERBINDUNGSQUELLEN",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 67 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:54",
       "fake": true,
       "field": "source.geo.country_name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:52",
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "KARTE DER VERBINDUNGSZIELE",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 14, "x": 5, "y": 67 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3255",
       "field": "destination.geo.location",
       "id": "2",
       "settings": { "precision": 3 },
       "type": "geohash_grid"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:3135",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "VERBINDUNGSZIELE",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 67 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:54",
       "fake": true,
       "field": "destination.geo.country_name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:52",
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "TRENNER",
   "type": "mxswat-separator-panel",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {}
   ]
  },
  {
   "title": "USV AUSLASTUNG IN %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "alias": "UPS Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ups_status",
     "select": [
      [
       { "params": [ "ups.load" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Watts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ups_status",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JAHRES VERBAUCH UND KOSTEN",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 80 },
   "yaxes": [
    { "format": "kwatth", "label": "LAST" }
   ],
   "targets": [
    {
     "alias": "KOSTEN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "SELECT sum(\"value\") *0.22/1000 FROM \"power\" WHERE \"host\" = 'mainpower' AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180*$kwhprice" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "SELECT sum(\"value\") FROM \"power\" WHERE \"host\" = 'mainpower' AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "KOSTEN HEUTE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180*$kwhprice" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "KOSTEN DIESE WOCHE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180*$kwhprice" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "KOSTEN AKT. MONAT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180*$kwhprice" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "JAHRESKOSTEN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180*$kwhprice" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GESCHÄTZTE JAHRESKOSTEN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1000*24*$kwhprice*365" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "USV",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 1, "x": 23, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Percent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ups_status",
     "select": [
      [
       { "params": [ "battery.charge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HEUTIGER VERBRAUCH",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "DIESE WOCHE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "DIESER MONAT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "DIESES JAHR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GESCHÄTZTER JAHRESVERBRAUCH",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1000*24*365" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "HDD TEMP",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 3, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_device",
     "select": [
      [
       { "params": [ "temp_c" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/.*/" }
     ]
    }
   ]
  },
  {
   "title": "UNRAID LOGs",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 86 },
   "targets": [
    {
     "expr": "{job=\"unraidsyslog\"} | json"
    }
   ]
  },
  {
   "title": "WIREGUARD VERBUNDEN",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 86 },
   "targets": [
    {
     "expr": "time()-wireguard_latest_handshake_seconds"
    }
   ]
  },
  {
   "title": "DATENDURCHSATZ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(wireguard_received_bytes_total{interface=\"wg0\",public_key=\"iB6Ft57prd30hGmUKEjOgzg8OeSYSN+ncIjbXaz2MC8=\"}[5m])",
     "legendFormat": "received {{friendly_name}}"
    },
    {
     "expr": "irate(wireguard_sent_bytes_total{interface=\"wg0\",public_key=\"iB6Ft57prd30hGmUKEjOgzg8OeSYSN+ncIjbXaz2MC8=\"}[5m])",
     "legendFormat": "sent {{friendly_name}}"
    }
   ]
  },
  {
   "title": "DATENDURCHSATZ",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(wireguard_received_bytes_total{interface=\"wg0\",public_key=\"iB6Ft57prd30hGmUKEjOgzg8OeSYSN+ncIjbXaz2MC8=\"}[5m])",
     "legendFormat": "received {{friendly_name}}"
    },
    {
     "expr": "irate(wireguard_sent_bytes_total{interface=\"wg0\",public_key=\"iB6Ft57prd30hGmUKEjOgzg8OeSYSN+ncIjbXaz2MC8=\"}[5m])",
     "legendFormat": "sent {{friendly_name}}"
    }
   ]
  },
  {
   "title": "S.M.A.R.T.",
   "type": "table",
   "description": "Note: Uses REGEX",
   "gridPos": { "h": 12, "w": 2, "x": 22, "y": 86 },
   "targets": [
    {
     "alias": "Temp",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "model" ], "type": "tag" },
      { "params": [ "serial_no" ], "type": "tag" },
      { "params": [ "fail" ], "type": "tag" },
      { "params": [ "flags" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Temp (C)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Temperature_Celsius" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_device",
     "select": [
      [
       { "params": [ "health_ok" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Health OK?" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Current Pending Sectors" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Current_Pending_Sector" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Reallocated Sectors" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Reallocated_Sector_Ct" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Reallocated Events" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Reallocated_Event_Count" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Offline/Uncorrectable" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Offline_Uncorrectable" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Power On Hours" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Power_On_Hours" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Power Cycles" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Power_Cycle_Count" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "Parity 02",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Helium Level" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Helium_Level" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "WIREGUARD VERBUNDEN",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "time()-wireguard_latest_handshake_seconds"
    }
   ]
  },
  {
   "title": "DATENDURCHSATZ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(wireguard_received_bytes_total{interface=\"wg0\",public_key=\"YB+YpAfE51mP14WEQbFvirC+cmjI7JJ9peYd+M8PFR8=\"}[5m])",
     "legendFormat": "received {{friendly_name}}"
    },
    {
     "expr": "irate(wireguard_sent_bytes_total{interface=\"wg0\",public_key=\"YB+YpAfE51mP14WEQbFvirC+cmjI7JJ9peYd+M8PFR8=\"}[5m])",
     "legendFormat": "sent {{friendly_name}}"
    }
   ]
  },
  {
   "title": "DATENDURCHSATZ",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(wireguard_received_bytes_total{interface=\"wg0\",public_key=\"YB+YpAfE51mP14WEQbFvirC+cmjI7JJ9peYd+M8PFR8=\"}[5m])",
     "legendFormat": "received {{friendly_name}}"
    },
    {
     "expr": "irate(wireguard_sent_bytes_total{interface=\"wg0\",public_key=\"YB+YpAfE51mP14WEQbFvirC+cmjI7JJ9peYd+M8PFR8=\"}[5m])",
     "legendFormat": "sent {{friendly_name}}"
    }
   ]
  },
  {
   "title": "UNRAID LOGIN WEBGUI",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 3, "y": 93 },
   "targets": [
    {
     "expr": "{job=\"unraidsyslog\"} |= \"webGUI\""
    }
   ]
  },
  {
   "title": "UNRAID LOGINS SSH",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 98 },
   "targets": [
    {
     "expr": "{job=\"unraidsyslog\"} |= \"ssh2\""
    }
   ]
  },
  {
   "title": "ONLINE ÜBERWACHUNG",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 98 },
   "targets": [
    {
     "expr": "sum((rate(probe_all_success_sum[$__range]) OR rate(probe_success_sum[$__range])) * on (instance, job, probe, config_version) group_left(check_name) max(sm_check_info{check_name=\"ping\", region=~\".*\"}) by (instance, job, probe, config_version, check_name)) by (instance, job, check_name) / sum((rate(probe_all_success_count[$__range]) OR rate(probe_success_count[$__range])) * on (instance, job, probe, config_version) group_left(check_name) max(sm_check_info{check_name=\"ping\", region=~\".*\"}) by (instance, job, probe, config_version, check_name)) by (instance, check_name, job)",
     "legendFormat": "{{check_name}}-{{instance}}-uptime"
    },
    {
     "expr": "sum((rate(probe_all_duration_seconds_sum[$__range]) OR rate(probe_duration_seconds_sum[$__range])) * on (instance, job, probe, config_version) group_left(check_name) max(sm_check_info{check_name=\"ping\", region=~\".*\"}) by (instance, job, probe, config_version, check_name)) by (instance, job, check_name) / sum((rate(probe_all_duration_seconds_count[$__range]) OR rate(probe_duration_seconds_count[$__range])) * on (instance, job, probe, config_version) group_left(check_name) max(sm_check_info{check_name=\"ping\", region=~\".*\"}) by (instance, job, probe, config_version, check_name)) by (instance, job, check_name)",
     "legendFormat": "{{check_name}}-{{instance}}-latency"
    }
   ]
  },
  {
   "type": "yesoreyeram-boomtheme-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {}
   ]
  }
 ]
}