{
 "title": "Traefik  Realtime Metrics",
 "description": "Visualize Traefik Metrics",
 "time": { "from": "2019-06-12T15:16:04.973Z", "to": "2019-06-12T15:23:54.753Z" },
 "panels": [
  {
   "title": "Average Response Time (ms)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(traefik_backend_request_duration_seconds_sum) / sum(traefik_backend_requests_total) * 1000"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_backend_requests_total{protocol=\"http\"})",
     "legendFormat": "{{http}}"
    },
    {
     "expr": "sum(traefik_backend_requests_total{protocol=\"https\"})",
     "legendFormat": "{{https}}"
    }
   ]
  },
  {
   "title": "404 Error Count last 5 Minutes",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{code=\"404\",method=\"GET\",protocol=\"http\"}[5m])) * 1000"
    }
   ]
  },
  {
   "title": "Requests by Request Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "traefik_backend_requests_total",
     "legendFormat": "{{protocol}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Requests in last 5 minutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total[5m]))",
     "legendFormat": "{{requests}}"
    }
   ]
  },
  {
   "title": "Successful Status Code Count (5min)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_backend_requests_total{protocol=~\"http|https\",code=\"200\"}[5m])",
     "legendFormat": "{{protocol}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Bad Status Code Count (5m)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_backend_requests_total{protocol=~\"http|https\",code!=\"200\"}[5m])",
     "legendFormat": "{{protocol}} {{method}} {{code}}"
    }
   ]
  }
 ]
}