{
 "title": "Traefik",
 "description": "Traefik dashboard with prometheus datasource prometheus",
 "tags": [
  "Prometheus",
  "Traefik"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "traefik" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_request_duration_seconds_sum) / sum(traefik_entrypoint_requests_total) * 1000"
    }
   ]
  },
  {
   "title": "Total requests over 5min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total[5m]))",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "Status code 200 over 5min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_entrypoint_requests_total{protocol=~\"http|https\",code=\"200\"}[5m])",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Others status code over 5min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_entrypoint_requests_total{protocol=~\"http|https\",code!=\"200\"}[5m])",
     "legendFormat": "{{ method }} : {{code}}"
    }
   ]
  }
 ]
}