{
 "title": "Traefik-Monitor",
 "description": "Traefik dashboard prometheus\n\nPrometheus监控traefik总览面板",
 "tags": [
  "traefik",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Cluster", "query": "label_values(k8scluster)" },
   {
    "name": "backend",
    "query": "label_values({k8scluster=\"$Cluster\"},backend)"
   }
  ]
 },
 "panels": [
  { "title": "全局监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "访问量占比",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(traefik_backend_requests_total{k8scluster =~ \"^$Cluster$\", backend=~\"^$backend$\"}) by (backend) ",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "非200状态码占比",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(traefik_backend_requests_total{k8scluster =~ \"^$Cluster$\", backend=~\"^$backend$\", code != \"200\"}) by (code) ",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "总访问量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_backend_requests_total{k8scluster=~\"^$Cluster$\", backend=~\"^$backend$\"}) by (backend)",
     "legendFormat": "{{ backend }}"
    }
   ]
  }
 ]
}