{
 "title": "Network Traffic Flow Analysis",
 "description": "A dashboard to display the various autonomous systems a router is communicating with.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "as",
    "label": "ASN",
    "query": "label_values(flow_transmit_bytes_total, destination_as)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(flow_receive_bytes_total, hostname)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Inbound Traffic by AS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(rate(flow_receive_bytes_total{source_as=~\"$as\",hostname=~\"$host\"}[1m]) * 8) by (source_as, source_as_name))",
     "legendFormat": "{{source_as_name}} (AS{{source_as}})"
    }
   ]
  },
  {
   "title": "Outbound Traffic by AS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(rate(flow_transmit_bytes_total{destination_as=~\"$as\",hostname=~\"$host\"}[1m]) * 8) by (destination_as, destination_as_name))",
     "legendFormat": "{{destination_as_name}} (AS{{destination_as}})"
    }
   ]
  },
  {
   "title": "Top Inbound ASNs",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "topk(10, sum(rate(flow_receive_bytes_total{source_as=~\"$as\",hostname=~\"$host\"}[$__range]) * 8) by (source_as, source_as_name))",
     "legendFormat": "{{source_as}}"
    }
   ]
  },
  {
   "title": "Top Outbound ASNs",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "topk(10, sum(rate(flow_transmit_bytes_total{destination_as=~\"$as\",hostname=~\"$host\"}[$__range]) * 8) by (destination_as, destination_as_name))"
    }
   ]
  }
 ]
}