{
 "title": "Transmission",
 "description": "Transmission statistics prometheus dashboard ",
 "tags": [
  "prometheus",
  "transmission"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Torrents", "query": "label_values(exported_name)" }
  ]
 },
 "panels": [
  {
   "title": "Number of torrents",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(transmission_torrent_done)"
    }
   ]
  },
  {
   "title": "Current ratio",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "transmission_session_stats_uploaded_bytes{type=\"current\"}/transmission_session_stats_downloaded_bytes{type=\"current\"}"
    }
   ]
  },
  {
   "title": "Current ratio",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "transmission_session_stats_uploaded_bytes{type=\"cumulative\"}/transmission_session_stats_downloaded_bytes{type=\"cumulative\"}"
    }
   ]
  },
  {
   "title": "Current download",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "transmission_session_stats_downloaded_bytes{type=\"current\"}"
    }
   ]
  },
  {
   "title": "Current upload",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "transmission_session_stats_uploaded_bytes{type=\"current\"}"
    }
   ]
  },
  {
   "title": "Total download",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "transmission_session_stats_downloaded_bytes{type=\"cumulative\"}"
    }
   ]
  },
  {
   "title": "Total upload",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "transmission_session_stats_uploaded_bytes{type=\"cumulative\"}"
    }
   ]
  },
  {
   "title": "Ratio $Torrents",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "transmission_torrent_ratio{exported_name=~\"$Torrents\"}",
     "legendFormat": "{{ exported_name }}"
    }
   ]
  }
 ]
}