{
 "title": "Spectrum Virtualize Overview",
 "description": "Dashboard for graphing IBM Spectrum Virtualize (like IBM Storwize V7000) using Prometheus as a data source.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(spectrum_temperature, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Frontend load [Bytes/s]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(spectrum_node_fc_bps{instance=~\"$instance\"}[5m])",
     "legendFormat": "FC node {{id}}"
    },
    {
     "expr": "avg_over_time(spectrum_node_iscsi_bps{instance=~\"$instance\"}[5m])",
     "legendFormat": "iSCSI node {{id}}"
    }
   ]
  },
  {
   "title": "Frontend load [IO/s]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(spectrum_node_fc_iops{instance=~\"$instance\"}[5m])",
     "legendFormat": "FC node {{id}}"
    },
    {
     "expr": "avg_over_time(spectrum_node_iscsi_iops{instance=~\"$instance\"}[5m])",
     "legendFormat": "iSCSI node {{id}}"
    }
   ]
  },
  {
   "title": "Backend load [Bytes/s]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(spectrum_node_sas_bps{instance=~\"$instance\"}[5m])",
     "legendFormat": "Node {{id}}"
    }
   ]
  },
  {
   "title": "Backend load [IO/s]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(spectrum_node_sas_iops{instance=~\"$instance\"}[5m])",
     "legendFormat": "Node {{id}}"
    }
   ]
  },
  {
   "title": "Pool usage [%]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "spectrum_pool_used_bytes{instance=~\"$instance\"}/spectrum_pool_capacity_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Interfaces unexpectedly down [#]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(spectrum_fc_port_status{instance=~\"$instance\",status=\"inactive_configured\"})",
     "legendFormat": "FC"
    }
   ]
  },
  {
   "title": "Power Usage [W]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "spectrum_power_watts{instance=~\"$instance\"}",
     "legendFormat": "Enclosure {{enclosure}}"
    }
   ]
  },
  {
   "title": "Interfaces unexpectedly down [#]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(spectrum_ip_port_state{instance=~\"$instance\",state=\"configured\"} == 1 and on (mac) spectrum_ip_port_link_active{instance=~\"$instance\"} == 0) or vector(0)",
     "legendFormat": "IP"
    }
   ]
  },
  {
   "title": "CPU usage [%]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "spectrum_node_compression_usage_ratio{instance=~\"$instance\"}",
     "legendFormat": "Compression CPU node {{id}}"
    },
    {
     "expr": "spectrum_node_system_usage_ratio{instance=~\"$instance\"}",
     "legendFormat": "System CPU node {{id}}"
    }
   ]
  },
  {
   "title": "Cache usage [%]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "spectrum_node_write_cache_usage_ratio{instance=~\"$instance\"}",
     "legendFormat": "Write cache node {{id}}"
    },
    {
     "expr": "spectrum_node_total_cache_usage_ratio{instance=~\"$instance\"}",
     "legendFormat": "Total cache node {{id}}"
    }
   ]
  }
 ]
}