{
 "title": "WavePlus Sensor",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Radon (Becquerels/m³)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "radon_short_term_avg_becquerels",
     "legendFormat": "short term"
    },
    { "expr": "radon_long_term_avg_becquerels", "legendFormat": "long term" }
   ]
  },
  {
   "title": "CO₂",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "carbondioxide_ppm" }
   ]
  },
  {
   "title": "VOC",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "voc_ppb" }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc( {job=\"waveplus\",__name__=~\"(radon_short_term).*\"} )",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": " {job=\"waveplus\",__name__=~\"carbon.*\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{job=\"waveplus\",__name__=~\"voc.*\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{job=\"waveplus\",__name__=~\"(humidity|temp|press).*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Radon (Becquerels/m³)",
   "type": "graph",
   "description": "[Radon](https://www.airthings.com/resources/radon-levels]) measurements are taken once every hour.  Wait at least a week (ideally a month) for accurate readings.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "Bq/m³" }
   ],
   "targets": [
    {
     "expr": "radon_short_term_avg_becquerels",
     "legendFormat": "short term"
    },
    {
     "expr": "radon_short_term_avg_becquerels * 1.1",
     "legendFormat": "+error short"
    },
    {
     "expr": "radon_short_term_avg_becquerels * .9",
     "legendFormat": "-error short"
    },
    { "expr": "radon_long_term_avg_becquerels", "legendFormat": "long term" },
    {
     "expr": "radon_long_term_avg_becquerels * 1.1",
     "legendFormat": "+error long"
    },
    {
     "expr": "radon_long_term_avg_becquerels * .9",
     "legendFormat": "-error long"
    },
    {
     "expr": "radon_short_term_avg_becquerels / 37",
     "legendFormat": "short term pci"
    }
   ]
  },
  {
   "title": "CO₂",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    { "expr": "carbondioxide_ppm", "legendFormat": "concentration" }
   ]
  },
  {
   "title": "VOC",
   "type": "graph",
   "description": "https://en.wikipedia.org/wiki/Volatile_organic_compound",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "conppb" }
   ],
   "targets": [
    { "expr": "voc_ppb", "legendFormat": "TVOC" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "temperature_celsius" },
    {
     "expr": "temperature_celsius * 9 / 5 + 32",
     "legendFormat": "F"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "humidity_percent" }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    { "expr": "pressure_pascal" }
   ]
  }
 ]
}