{
 "title": "Workload Resource Recommendations Based on Usage",
 "description": "Looks at historical resource usage of Kubernetes pods associated with any controller, and recommends requests/limits accordingly",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "controller",
    "query": {
     "query": "label_values(kube_pod_owner{namespace=\"$namespace\"},owner_name)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{cluster=\"$cluster\", namespace=\"$namespace\",pod=~\"$controller(.*)\"}, container)"
    }
   },
   { "name": "recommendation_time_considered", "query": "1h,3h,6h,12h,24h,1d,2d" },
   { "name": "overhead", "query": "1.25,1.1,1.05,1.5" }
  ]
 },
 "panels": [
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod=~\"$controller(.*)\", cluster=\"$cluster\", container=~\"$container\"}) by (pod)",
     "legendFormat": "{{pod}} - {{container}}"
    },
    {
     "expr": "sum(avg(kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$controller(.*)\", resource=\"cpu\", container=~\"$container\"}) by (container))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(avg(kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$controller(.*)\", resource=\"cpu\", container=~\"$container\"}) by (container))\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Suggested CPU Request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "CPU" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "$overhead * sum(max(quantile_over_time(0.95,sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod=~\"$controller(.*)\", cluster=\"$cluster\", container=~\"$container\"}) by (pod,namespace,container)[$recommendation_time_considered:15m]) * on(pod,namespace) group_left(owner) kube_pod_owner{owner_name=\"$controller\"}) by (container))"
    }
   ]
  },
  {
   "title": "Suggested CPU Limit",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "CPU" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "2 * $overhead * sum(max(quantile_over_time(0.95,sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod=~\"$controller(.*)\", cluster=\"$cluster\", container=~\"$container\"}) by (pod,namespace,container)[$recommendation_time_considered:15m]) * on(pod,namespace) group_left(owner) kube_pod_owner{owner_name=\"$controller\"}) by (container))"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$controller(.*)\", container!=\"\", image!=\"\", container=~\"$container\"}) by (pod, container)",
     "legendFormat": "{{pod}} - {{container}}"
    },
    {
     "expr": "sum(\n    avg(\n      kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$controller(.*)\", resource=\"memory\", container=~\"$container\"}\n    ) by (container)\n)\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    avg(\n      kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$controller(.*)\", resource=\"memory\", container=~\"$container\"}\n    ) by (container)\n)\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Suggested Memory Request",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "$overhead * sum(max(avg(quantile_over_time(0.95,container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$controller(.*)\", container!=\"\", image!=\"\", container=~\"$container\"}[$recommendation_time_considered])) by (pod,namespace,container) * on(pod,namespace) group_left(owner) kube_pod_owner{owner_name=\"$controller\"}) by (container)) "
    }
   ]
  },
  {
   "title": "Suggested Memory Limit",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "$overhead * sum(max(avg(quantile_over_time(0.95,container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$controller(.*)\", container!=\"\", image!=\"\", container=~\"$container\"}[$recommendation_time_considered])) by (pod,namespace,container) * on(pod,namespace) group_left(owner) kube_pod_owner{owner_name=\"$controller\"}) by (container)) "
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=~\"$controller(.*)\", container!=\"\", cluster=\"$cluster\"}[5m])) by (pod,container) /sum(increase(container_cpu_cfs_periods_total{namespace=\"$namespace\", pod=~\"$controller(.*)\", container!=\"\", cluster=\"$cluster\"}[5m])) by (pod,container)",
     "legendFormat": "{{pod}} - {{container}}"
    }
   ]
  },
  { "title": "CPU Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU Quota",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$controller(.*)\"}) by (pod,container)) by (container)"
    },
    {
     "expr": "avg(sum(kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$controller(.*)\", resource=\"cpu\"}) by (pod,container)) by (container)"
    },
    {
     "expr": "avg(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$controller(.*)\"}) by (pod,container)) by (container) / avg(sum(kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$controller(.*)\", resource=\"cpu\"}) by (pod,container)) by (container)"
    },
    {
     "expr": "avg(sum(kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$controller(.*)\", resource=\"cpu\"}) by (pod,container)) by (container)"
    },
    {
     "expr": "avg(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$controller(.*)\"}) by (pod,container)) by (container) / avg(sum(kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$controller(.*)\", resource=\"cpu\"}) by (pod,container)) by (container)"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  { "title": "Memory Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Memory Quota",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$controller(.*)\", container!=\"\", image!=\"\"}) by (pod,container)) by (container)"
    },
    {
     "expr": "avg(sum(kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$controller(.*)\", resource=\"memory\"}) by (pod,container)) by (container)"
    },
    {
     "expr": "avg(sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$controller(.*)\", image!=\"\"}) by (pod,container)) by (container) / avg(sum(kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$controller(.*)\", resource=\"memory\"}) by (pod,container)) by (container)"
    },
    {
     "expr": "avg(sum(kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$controller(.*)\", resource=\"memory\"}) by (pod,container)) by (container)"
    },
    {
     "expr": "avg(sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$controller(.*)\", container!=\"\", image!=\"\"}) by (pod,container)) by (container) / avg(sum(kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$controller(.*)\", resource=\"memory\"}) by (pod,container)) by (container)"
    },
    {
     "expr": "avg(sum(container_memory_rss{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$controller(.*)\", container != \"\", container != \"POD\"}) by (pod,container)) by (container)"
    },
    {
     "expr": "avg(sum(container_memory_cache{cluster=\"$cluster\", namespace=\"$namespace\",pod=~\"$controller(.*)\", container != \"\", container != \"POD\"})  by (pod,container)) by (container)"
    },
    {
     "expr": "avg(sum(container_memory_swap{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$controller(.*)\", container != \"\", container != \"POD\"})  by (pod,container)) by (container)"
    }
   ]
  }
 ]
}