apiVersion: traefik.containo.us/v1alpha1
kind:       Middleware
metadata:
  name: webauth-secret
spec:
  basicAuth:
    secret: webauth-secret
---
apiVersion: traefik.containo.us/v1alpha1
kind:       Middleware
metadata:
  name: to-https
spec:
  redirectScheme:
    scheme:    https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ratelimit
spec:
  rateLimit:
    average: 100
    burst:   500
# ---
{{/*apiVersion: traefik.containo.us/v1alpha1*/}}
{{/*kind:       Middleware*/}}
{{/*metadata:*/}}
{{/*  name: cors-header*/}}
{{/*spec:*/}}
{{/*  headers:*/}}
{{/*    accessControlAllowMethods:*/}}
{{/*      - "GET"*/}}
{{/*      - "OPTIONS"*/}}
{{/*      - "POST"*/}}
{{/*      - "PATCH"*/}}
{{/*      - "DELETE"*/}}
{{/*      - "PUT"*/}}
{{/*    accessControlAllowOriginList:*/}}
{{/*      - "*"*/}}
{{/*    customResponseHeaders:*/}}
{{/*      Access-Control-Allow-Origin: "*"*/}}
{{/*    accessControlAllowCredentials: True*/}}
{{/*    addVaryHeader: True*/}}
{{/*---*/}}
