apiVersion: v1
kind: Secret
metadata:
  name: webauth-secret
  namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: default
data:
  users:
    {{{{ webauth_secret }}}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{{{ do_auth_token_name }}}}
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: default
data:
  DO_AUTH_TOKEN: {{{{ do_auth_token_value }}}}
---
apiVersion: v1
kind: Secret
metadata:
  name: sftp-private-key
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: default
  namespace: default
data:
  key: >-
    {{{{ sftp_private_key_base64_encoded }}}}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: {{{{ image_pull_secret_name }}}}
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: default
  namespace: default
data:
  .dockerconfigjson: >-
    {{{{ image_pull_secret }}}}
type: kubernetes.io/dockerconfigjson
