apiVersion: v1
kind: Secret
metadata:
  name: webauth-secret
  namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: default
data:
  users:
    YWRtaW46JGFwcjEkMmVpczQzbnUkQ0w4YXlMRlMwMExkWEZLbkdyRzI3Lw==
---
apiVersion: v1
kind: Secret
metadata:
  name: do-auth-token
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: default
data:
  DO_AUTH_TOKEN: cab2a40e-f872-48f5-998f-4eacdee63e6c
---
apiVersion: v1
kind: Secret
metadata:
  name: sftp-private-key
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: default
  namespace: default
data:
  key: >-
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDWEFJQkFBS0JnUUNuRjBwb09XeFNmKzd6MlhsYk96cVVTYWtrckI4UkZSYTF3VVJqYldvdzNFVHpPUXp4CmNxQUt1d2I3VUxTdUM3dXNEbDNWTWdwV3RwbUJaeVpwWUpUa1E4dzVQaGR0SklSNlBpRFF3N01xMFg1YkFPK0cKaVQ5UEYrU0VhQktTWXNTNzMwS3pTRjN4S0hPaC9zd0hPTGhJazBIZUQ4NGlqR3FpZWFNc3RSQjUvUUlEQVFBQgpBb0dBRmhBTHVaNVhjTDlHd0hrSFBxWWY4b09WYTJ1MHdHOHQ2L3JrZWxKd3NwbnJHc2grTG9WcG4zRVpsMmFOCkxPd01zRWZIV1FhOStid3JvYndLaE9DRldEV04rMFZidmRwb0l0bHJMNTFaenNRVVZuTXF3L2pqZ0U0MGdrVzUKZk4rbmx4SjRnVnFHSnhkSGljQ0tmYU5PalFzbG1NZVNKUVppdW8wc3U3WGtoK3NDUVFDMXRzM2FTT0UxSTQ0TgpRdVRra0JUVWQ4K25yR3RBWTk0cG5UbnBrNldJYXpmc3dKT3djeXViRWNNL3RudkN3by8xaHdUcWNsT2lkbzBqCmYyZWZRMlNQQWtFQTYyWWRCelhjUTdFT2RpNEVlQm13a0tUSS9FNEJBbzJTWmZheEVWTkpha251M0NRVlBRV1oKdGpCVTdnYWRXWlZ5UnBaNlJGbDM1TFd0MDdaOS9oVTJzd0pBYTVFU0hIUmw5RG5lM2hUS1FFN1dOY3ZTdmRRQQpEVGJSRFZ0SUsrKzkzcHB4bVpHS0c3cWhob01tVEhIdW95VGZhUjJMR0dtaS9wb2xCRzFuM3N4Ykd3SkFQa0hxCmlYNm9POHIzTFRCc2hDc2ZOSkl3aWZKRGVCNWpTczVjOUYwWHZLSERKN3Z2VmcxR0l4WlRVQVMxMXZ5Y2xhaTAKdTZFQ0FaNC9WQkFlOEhWQjJ3SkJBSldrZ1dOK1ZTaktLZDV5RERub0RSWGZnSUt6d1VBeVI2VU5nUW1XUWIwTwpXQm5GL2IrMlg4dlhtZXI1QnVMdHRoczlBMDJIeC94M3FxTEpxL1dSS2lRPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ==
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub
  labels:
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: default
  namespace: default
data:
  .dockerconfigjson: >-
    cab2a40e-f872-48f5-998f-4eacdee63e6c
type: kubernetes.io/dockerconfigjson
